<a href="https://colab.research.google.com/github/cypherkrish/PythonDataScience/blob/main/04_DS_Pandas_Basics.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import pandas as pd
import numpy as np

In [ ]:
# help(pd.Series) # this is to get the help

#**Series in Pandas**

In [ ]:
my_index = ['USA', 'Canada', 'Maxico']

In [ ]:
my_data = [1776, 1867, 1821]

In [ ]:
my_series = pd.Series(my_data)

In [ ]:
my_series

0    1776
1    1867
2    1821
dtype: int64

In [ ]:
type(my_series)

pandas.core.series.Series

In [ ]:
my_series= pd.Series (my_data, my_index )

In [ ]:
my_series

USA       1776
Canada    1867
Maxico    1821
dtype: int64

In [ ]:
type(my_series)

pandas.core.series.Series

In [ ]:
my_series[0]

1776

In [ ]:
my_series['USA']

1776

In [ ]:
# Using dictionary

ages = { 'sam':5, 'frank': 10, 'spike': 7}

In [ ]:
ages

{'sam': 5, 'frank': 10, 'spike': 7}

In [ ]:
pd.Series(ages)

sam       5
frank    10
spike     7
dtype: int64

In [ ]:
# Example

expenses = pd.Series({'Andrew':200,'Bob':150,'Claire':450})

In [ ]:
expenses

Andrew    200
Bob       150
Claire    450
dtype: int64

In [ ]:
expenses['Bob']

150

In [ ]:
# Pandas Series Operations

In [ ]:
q1 = {'Japan': 80, 'China': 450, 'India': 200, 'USA': 250}
q2 = {'Brazil': 100,'China': 500, 'India': 210,'USA': 260}

In [ ]:
sales_q1 = pd.Series(q1)

In [ ]:
sales_q2 = pd.Series(q2)

In [ ]:
sales_q1

Japan     80
China    450
India    200
USA      250
dtype: int64

In [ ]:
sales_q2

Brazil    100
China     500
India     210
USA       260
dtype: int64

In [ ]:
sales_q1['Japan']

80

In [ ]:
sales_q1[0]

80

In [ ]:
sales_q1.keys()

Index(['Japan', 'China', 'India', 'USA'], dtype='object')

In [ ]:
[1, 2] * 2

[1, 2, 1, 2]

In [ ]:
np.array([1, 2]) * 2

array([2, 4])

In [ ]:
sales_q1 /100

Japan    0.8
China    4.5
India    2.0
USA      2.5
dtype: float64

In [ ]:
sales_q1

Japan     80
China    450
India    200
USA      250
dtype: int64

In [ ]:
sales_q2

Brazil    100
China     500
India     210
USA       260
dtype: int64

In [ ]:
sales_q1 + sales_q2

Brazil      NaN
China     950.0
India     410.0
Japan       NaN
USA       510.0
dtype: float64

In [ ]:
sales_q1.add(sales_q2)

Brazil      NaN
China     950.0
India     410.0
Japan       NaN
USA       510.0
dtype: float64

In [ ]:
sales_q1.add(sales_q2, fill_value=0)

Brazil    100.0
China     950.0
India     410.0
Japan      80.0
USA       510.0
dtype: float64

In [ ]:
first_half = sales_q1.add(sales_q2, fill_value=0)

In [ ]:
sales_q1.dtype

dtype('int64')

In [ ]:
sales_q2.dtype

dtype('int64')

In [ ]:
first_half.dtype

dtype('float64')

# **DataFrames**

In [ ]:
import numpy as np
import pandas as pd

In [ ]:
np.random.seed(101)
mydata = np.random.randint(0, 101, (4, 3))

In [ ]:
mydata

array([[95, 11, 81],
       [70, 63, 87],
       [75,  9, 77],
       [40,  4, 63]])

In [ ]:
myindex = ['CA', 'NY', 'AZ', 'TX']

In [ ]:
mycolumns = ['Jan', 'Feb', 'Mar']

In [ ]:
df = pd.DataFrame(mydata, index = myindex , columns = mycolumns)

In [ ]:
df

    Jan  Feb  Mar
CA   95   11   81
NY   70   63   87
AZ   75    9   77
TX   40    4   63

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 4 entries, CA to TX
Data columns (total 3 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   Jan     4 non-null      int64
 1   Feb     4 non-null      int64
 2   Mar     4 non-null      int64
dtypes: int64(3)
memory usage: 128.0+ bytes

In [ ]:
# Read CSV files

In [ ]:
df = pd.read_csv("https://raw.githubusercontent.com/cypherkrish/PythonDataScience/main/Data/tips.csv")

In [ ]:
df.head()

,total_bill,tip,sex,smoker,day,time,size,price_per_person,Payer Name,CC Number,Payment ID
0,16.99,1.01,Female,No,Sun,Dinner,2,8.49,Christy Cunningham,3560325168603410,Sun2959
1,10.34,1.66,Male,No,Sun,Dinner,3,3.45,Douglas Tucker,4478071379779230,Sun4608
2,21.01,3.50,Male,No,Sun,Dinner,3,7.00,Travis Walters,6011812112971322,Sun4458
3,23.68,3.31,Male,No,Sun,Dinner,2,11.84,Nathaniel Harris,4676137647685994,Sun5260
4,24.59,3.61,Female,No,Sun,Dinner,4,6.15,Tonya Carter,4832732618637221,Sun2251

In [ ]:
df.columns

Index(['total_bill', 'tip', 'sex', 'smoker', 'day', 'time', 'size',
       'price_per_person', 'Payer Name', 'CC Number', 'Payment ID'],
      dtype='object')

In [ ]:
df.index

RangeIndex(start=0, stop=244, step=1)

In [ ]:
df.tail()

,total_bill,tip,sex,smoker,day,time,size,price_per_person,Payer Name,CC Number,Payment ID
239,29.03,5.92,Male,No,Sat,Dinner,3,9.68,Michael Avila,5296068606052842,Sat2657
240,27.18,2.00,Female,Yes,Sat,Dinner,2,13.59,Monica Sanders,3506806155565404,Sat1766
241,22.67,2.00,Male,Yes,Sat,Dinner,2,11.34,Keith Wong,6011891618747196,Sat3880
242,17.82,1.75,Male,No,Sat,Dinner,2,8.91,Dennis Dixon,4375220550950,Sat17
243,18.78,3.00,Female,No,Thur,Dinner,2,9.39,Michelle Hardin,3511451626698139,Thur672

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 244 entries, 0 to 243
Data columns (total 11 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   total_bill        244 non-null    float64
 1   tip               244 non-null    float64
 2   sex               244 non-null    object
 3   smoker            244 non-null    object
 4   day               244 non-null    object
 5   time              244 non-null    object
 6   size              244 non-null    int64
 7   price_per_person  244 non-null    float64
 8   Payer Name        244 non-null    object
 9   CC Number         244 non-null    int64
 10  Payment ID        244 non-null    object
dtypes: float64(3), int64(2), object(6)
memory usage: 21.1+ KB

In [ ]:
df.describe()

       total_bill         tip        size  price_per_person     CC Number
count  244.000000  244.000000  244.000000        244.000000  2.440000e+02
mean    19.785943    2.998279    2.569672          7.888197  2.563496e+15
std      8.902412    1.383638    0.951100          2.914234  2.369340e+15
min      3.070000    1.000000    1.000000          2.880000  6.040679e+10
25%     13.347500    2.000000    2.000000          5.800000  3.040731e+13
50%     17.795000    2.900000    2.000000          7.255000  3.525318e+15
75%     24.127500    3.562500    3.000000          9.390000  4.553675e+15
max     50.810000   10.000000    6.000000         20.270000  6.596454e+15

In [ ]:
df.describe().transpose()

,count,mean,std,min,25%,50%,75%,max
total_bill,244.0,1.978594e+01,8.902412e+00,3.070000e+00,1.334750e+01,1.779500e+01,2.412750e+01,5.081000e+01
tip,244.0,2.998279e+00,1.383638e+00,1.000000e+00,2.000000e+00,2.900000e+00,3.562500e+00,1.000000e+01
size,244.0,2.569672e+00,9.510998e-01,1.000000e+00,2.000000e+00,2.000000e+00,3.000000e+00,6.000000e+00
price_per_person,244.0,7.888197e+00,2.914234e+00,2.880000e+00,5.800000e+00,7.255000e+00,9.390000e+00,2.027000e+01
CC Number,244.0,2.563496e+15,2.369340e+15,6.040679e+10,3.040731e+13,3.525318e+15,4.553675e+15,6.596454e+15

## DataFrame - Columns

In [ ]:
df['total_bill']

0      16.99
1      10.34
2      21.01
3      23.68
4      24.59
       ...
239    29.03
240    27.18
241    22.67
242    17.82
243    18.78
Name: total_bill, Length: 244, dtype: float64

In [ ]:
type(df['total_bill'])

pandas.core.series.Series

In [ ]:
mycols = ['total_bill', 'tip']
df[mycols]

     total_bill   tip
0         16.99  1.01
1         10.34  1.66
2         21.01  3.50
3         23.68  3.31
4         24.59  3.61
..          ...   ...
239       29.03  5.92
240       27.18  2.00
241       22.67  2.00
242       17.82  1.75
243       18.78  3.00

[244 rows x 2 columns]

In [ ]:
df[['total_bill', 'tip']]

     total_bill   tip
0         16.99  1.01
1         10.34  1.66
2         21.01  3.50
3         23.68  3.31
4         24.59  3.61
..          ...   ...
239       29.03  5.92
240       27.18  2.00
241       22.67  2.00
242       17.82  1.75
243       18.78  3.00

[244 rows x 2 columns]

In [ ]:
df['tip'] + df['total_bill']

0      18.00
1      12.00
2      24.51
3      26.99
4      28.20
       ...
239    34.95
240    29.18
241    24.67
242    19.57
243    21.78
Length: 244, dtype: float64

In [ ]:
100 * (df['tip'] / df['total_bill'])

0       5.944673
1      16.054159
2      16.658734
3      13.978041
4      14.680765
         ...
239    20.392697
240     7.358352
241     8.822232
242     9.820426
243    15.974441
Length: 244, dtype: float64

In [ ]:
df['tip_percentage'] = 100 * (df['tip'] / df['total_bill'])

In [ ]:
df.head()

,total_bill,tip,sex,smoker,day,time,size,price_per_person,Payer Name,CC Number,Payment ID,tip_percentage
0,16.99,1.01,Female,No,Sun,Dinner,2,8.49,Christy Cunningham,3560325168603410,Sun2959,5.944673
1,10.34,1.66,Male,No,Sun,Dinner,3,3.45,Douglas Tucker,4478071379779230,Sun4608,16.054159
2,21.01,3.50,Male,No,Sun,Dinner,3,7.00,Travis Walters,6011812112971322,Sun4458,16.658734
3,23.68,3.31,Male,No,Sun,Dinner,2,11.84,Nathaniel Harris,4676137647685994,Sun5260,13.978041
4,24.59,3.61,Female,No,Sun,Dinner,4,6.15,Tonya Carter,4832732618637221,Sun2251,14.680765

In [ ]:
df['price_per_person'] = df['total_bill'] / df['size']

In [ ]:
np.round

In [ ]:
df.head()

,total_bill,tip,sex,smoker,day,time,size,price_per_person,Payer Name,CC Number,Payment ID,tip_percentage
0,16.99,1.01,Female,No,Sun,Dinner,2,8.495000,Christy Cunningham,3560325168603410,Sun2959,5.944673
1,10.34,1.66,Male,No,Sun,Dinner,3,3.446667,Douglas Tucker,4478071379779230,Sun4608,16.054159
2,21.01,3.50,Male,No,Sun,Dinner,3,7.003333,Travis Walters,6011812112971322,Sun4458,16.658734
3,23.68,3.31,Male,No,Sun,Dinner,2,11.840000,Nathaniel Harris,4676137647685994,Sun5260,13.978041
4,24.59,3.61,Female,No,Sun,Dinner,4,6.147500,Tonya Carter,4832732618637221,Sun2251,14.680765

In [ ]:
df['price_per_person']

0       8.495000
1       3.446667
2       7.003333
3      11.840000
4       6.147500
         ...
239     9.676667
240    13.590000
241    11.335000
242     8.910000
243     9.390000
Name: price_per_person, Length: 244, dtype: float64

In [ ]:
df['price_per_person'] = np.round(df['total_bill'] / df['size'],2)

In [ ]:
df.head()

,total_bill,tip,sex,smoker,day,time,size,price_per_person,Payer Name,CC Number,Payment ID,tip_percentage
0,16.99,1.01,Female,No,Sun,Dinner,2,8.49,Christy Cunningham,3560325168603410,Sun2959,5.944673
1,10.34,1.66,Male,No,Sun,Dinner,3,3.45,Douglas Tucker,4478071379779230,Sun4608,16.054159
2,21.01,3.50,Male,No,Sun,Dinner,3,7.00,Travis Walters,6011812112971322,Sun4458,16.658734
3,23.68,3.31,Male,No,Sun,Dinner,2,11.84,Nathaniel Harris,4676137647685994,Sun5260,13.978041
4,24.59,3.61,Female,No,Sun,Dinner,4,6.15,Tonya Carter,4832732618637221,Sun2251,14.680765

In [ ]:
df['price_per_person']

0       8.49
1       3.45
2       7.00
3      11.84
4       6.15
       ...
239     9.68
240    13.59
241    11.34
242     8.91
243     9.39
Name: price_per_person, Length: 244, dtype: float64

In [ ]:
# We can drop columns if not required

In [ ]:
df.drop('tip_percentage', axis=1)

,total_bill,tip,sex,smoker,day,time,size,price_per_person,Payer Name,CC Number,Payment ID
0,16.99,1.01,Female,No,Sun,Dinner,2,8.49,Christy Cunningham,3560325168603410,Sun2959
1,10.34,1.66,Male,No,Sun,Dinner,3,3.45,Douglas Tucker,4478071379779230,Sun4608
2,21.01,3.50,Male,No,Sun,Dinner,3,7.00,Travis Walters,6011812112971322,Sun4458
3,23.68,3.31,Male,No,Sun,Dinner,2,11.84,Nathaniel Harris,4676137647685994,Sun5260
4,24.59,3.61,Female,No,Sun,Dinner,4,6.15,Tonya Carter,4832732618637221,Sun2251
...,...,...,...,...,...,...,...,...,...,...,...
239,29.03,5.92,Male,No,Sat,Dinner,3,9.68,Michael Avila,5296068606052842,Sat2657
240,27.18,2.00,Female,Yes,Sat,Dinner,2,13.59,Monica Sanders,3506806155565404,Sat1766
241,22.67,2.00,Male,Yes,Sat,Dinner,2,11.34,Keith Wong,6011891618747196,Sat3880
242,17.82,1.75,Male,No,Sat,Dinner,2,8.91,Dennis Dixon,4375220550950,Sat17
243,18.78,3.00,Female,No,Thur,Dinner,2,9.39,Michelle Hardin,3511451626698139,Thur672

In [ ]:
df.head()

,total_bill,tip,sex,smoker,day,time,size,price_per_person,Payer Name,CC Number,Payment ID,tip_percentage
0,16.99,1.01,Female,No,Sun,Dinner,2,8.49,Christy Cunningham,3560325168603410,Sun2959,5.944673
1,10.34,1.66,Male,No,Sun,Dinner,3,3.45,Douglas Tucker,4478071379779230,Sun4608,16.054159
2,21.01,3.50,Male,No,Sun,Dinner,3,7.00,Travis Walters,6011812112971322,Sun4458,16.658734
3,23.68,3.31,Male,No,Sun,Dinner,2,11.84,Nathaniel Harris,4676137647685994,Sun5260,13.978041
4,24.59,3.61,Female,No,Sun,Dinner,4,6.15,Tonya Carter,4832732618637221,Sun2251,14.680765

In [ ]:
df = df.drop('tip_percentage', axis=1)

In [ ]:
df.head()

,total_bill,tip,sex,smoker,day,time,size,price_per_person,Payer Name,CC Number,Payment ID
0,16.99,1.01,Female,No,Sun,Dinner,2,8.49,Christy Cunningham,3560325168603410,Sun2959
1,10.34,1.66,Male,No,Sun,Dinner,3,3.45,Douglas Tucker,4478071379779230,Sun4608
2,21.01,3.50,Male,No,Sun,Dinner,3,7.00,Travis Walters,6011812112971322,Sun4458
3,23.68,3.31,Male,No,Sun,Dinner,2,11.84,Nathaniel Harris,4676137647685994,Sun5260
4,24.59,3.61,Female,No,Sun,Dinner,4,6.15,Tonya Carter,4832732618637221,Sun2251

In [ ]:
df.shape

(244, 11)

In [ ]:
df.head()

,total_bill,tip,sex,smoker,day,time,size,price_per_person,Payer Name,CC Number,Payment ID
0,16.99,1.01,Female,No,Sun,Dinner,2,8.49,Christy Cunningham,3560325168603410,Sun2959
1,10.34,1.66,Male,No,Sun,Dinner,3,3.45,Douglas Tucker,4478071379779230,Sun4608
2,21.01,3.50,Male,No,Sun,Dinner,3,7.00,Travis Walters,6011812112971322,Sun4458
3,23.68,3.31,Male,No,Sun,Dinner,2,11.84,Nathaniel Harris,4676137647685994,Sun5260
4,24.59,3.61,Female,No,Sun,Dinner,4,6.15,Tonya Carter,4832732618637221,Sun2251

In [ ]:
df.index

RangeIndex(start=0, stop=244, step=1)

In [ ]:
# Here 'Payment ID' is a uniqueue value for each row, so we can setup this as the index

In [ ]:
df.set_index("Payment ID")

,total_bill,tip,sex,smoker,day,time,size,price_per_person,Payer Name,CC Number
Payment ID,,,,,,,,,,
Sun2959,16.99,1.01,Female,No,Sun,Dinner,2,8.49,Christy Cunningham,3560325168603410
Sun4608,10.34,1.66,Male,No,Sun,Dinner,3,3.45,Douglas Tucker,4478071379779230
Sun4458,21.01,3.50,Male,No,Sun,Dinner,3,7.00,Travis Walters,6011812112971322
Sun5260,23.68,3.31,Male,No,Sun,Dinner,2,11.84,Nathaniel Harris,4676137647685994
Sun2251,24.59,3.61,Female,No,Sun,Dinner,4,6.15,Tonya Carter,4832732618637221
...,...,...,...,...,...,...,...,...,...,...
Sat2657,29.03,5.92,Male,No,Sat,Dinner,3,9.68,Michael Avila,5296068606052842
Sat1766,27.18,2.00,Female,Yes,Sat,Dinner,2,13.59,Monica Sanders,3506806155565404
Sat3880,22.67,2.00,Male,Yes,Sat,Dinner,2,11.34,Keith Wong,6011891618747196
Sat17,17.82,1.75,Male,No,Sat,Dinner,2,8.91,Dennis Dixon,4375220550950
Thur672,18.78,3.00,Female,No,Thur,Dinner,2,9.39,Michelle Hardin,3511451626698139

In [ ]:
df.shape

(244, 11)

In [ ]:
df = df.set_index("Payment ID")

In [ ]:
df.shape

(244, 10)

In [ ]:
df.head()

,total_bill,tip,sex,smoker,day,time,size,price_per_person,Payer Name,CC Number
Payment ID,,,,,,,,,,
Sun2959,16.99,1.01,Female,No,Sun,Dinner,2,8.49,Christy Cunningham,3560325168603410
Sun4608,10.34,1.66,Male,No,Sun,Dinner,3,3.45,Douglas Tucker,4478071379779230
Sun4458,21.01,3.50,Male,No,Sun,Dinner,3,7.00,Travis Walters,6011812112971322
Sun5260,23.68,3.31,Male,No,Sun,Dinner,2,11.84,Nathaniel Harris,4676137647685994
Sun2251,24.59,3.61,Female,No,Sun,Dinner,4,6.15,Tonya Carter,4832732618637221

In [ ]:
# Change the index to column

In [ ]:
df.reset_index()

,Payment ID,total_bill,tip,sex,smoker,day,time,size,price_per_person,Payer Name,CC Number
0,Sun2959,16.99,1.01,Female,No,Sun,Dinner,2,8.49,Christy Cunningham,3560325168603410
1,Sun4608,10.34,1.66,Male,No,Sun,Dinner,3,3.45,Douglas Tucker,4478071379779230
2,Sun4458,21.01,3.50,Male,No,Sun,Dinner,3,7.00,Travis Walters,6011812112971322
3,Sun5260,23.68,3.31,Male,No,Sun,Dinner,2,11.84,Nathaniel Harris,4676137647685994
4,Sun2251,24.59,3.61,Female,No,Sun,Dinner,4,6.15,Tonya Carter,4832732618637221
...,...,...,...,...,...,...,...,...,...,...,...
239,Sat2657,29.03,5.92,Male,No,Sat,Dinner,3,9.68,Michael Avila,5296068606052842
240,Sat1766,27.18,2.00,Female,Yes,Sat,Dinner,2,13.59,Monica Sanders,3506806155565404
241,Sat3880,22.67,2.00,Male,Yes,Sat,Dinner,2,11.34,Keith Wong,6011891618747196
242,Sat17,17.82,1.75,Male,No,Sat,Dinner,2,8.91,Dennis Dixon,4375220550950
243,Thur672,18.78,3.00,Female,No,Thur,Dinner,2,9.39,Michelle Hardin,3511451626698139

In [ ]:
df = df.reset_index()

In [ ]:
df.shape

(244, 11)

In [ ]:
df.head()

,Payment ID,total_bill,tip,sex,smoker,day,time,size,price_per_person,Payer Name,CC Number
0,Sun2959,16.99,1.01,Female,No,Sun,Dinner,2,8.49,Christy Cunningham,3560325168603410
1,Sun4608,10.34,1.66,Male,No,Sun,Dinner,3,3.45,Douglas Tucker,4478071379779230
2,Sun4458,21.01,3.50,Male,No,Sun,Dinner,3,7.00,Travis Walters,6011812112971322
3,Sun5260,23.68,3.31,Male,No,Sun,Dinner,2,11.84,Nathaniel Harris,4676137647685994
4,Sun2251,24.59,3.61,Female,No,Sun,Dinner,4,6.15,Tonya Carter,4832732618637221

In [ ]:
df = df.set_index("Payment ID")

In [ ]:
df.head()

,total_bill,tip,sex,smoker,day,time,size,price_per_person,Payer Name,CC Number
Payment ID,,,,,,,,,,
Sun2959,16.99,1.01,Female,No,Sun,Dinner,2,8.49,Christy Cunningham,3560325168603410
Sun4608,10.34,1.66,Male,No,Sun,Dinner,3,3.45,Douglas Tucker,4478071379779230
Sun4458,21.01,3.50,Male,No,Sun,Dinner,3,7.00,Travis Walters,6011812112971322
Sun5260,23.68,3.31,Male,No,Sun,Dinner,2,11.84,Nathaniel Harris,4676137647685994
Sun2251,24.59,3.61,Female,No,Sun,Dinner,4,6.15,Tonya Carter,4832732618637221

In [ ]:
# Grab or accesss the specified record

In [ ]:
df.iloc[0]

total_bill                       16.99
tip                               1.01
sex                             Female
smoker                              No
day                                Sun
time                            Dinner
size                                 2
price_per_person                  8.49
Payer Name          Christy Cunningham
CC Number             3560325168603410
Name: Sun2959, dtype: object

In [ ]:
df.loc['Sun2959']  # Using the index value

total_bill                       16.99
tip                               1.01
sex                             Female
smoker                              No
day                                Sun
time                            Dinner
size                                 2
price_per_person                  8.49
Payer Name          Christy Cunningham
CC Number             3560325168603410
Name: Sun2959, dtype: object

In [ ]:
## Access specified rows using locaction

df.iloc[0:4]

,total_bill,tip,sex,smoker,day,time,size,price_per_person,Payer Name,CC Number
Payment ID,,,,,,,,,,
Sun2959,16.99,1.01,Female,No,Sun,Dinner,2,8.49,Christy Cunningham,3560325168603410
Sun4608,10.34,1.66,Male,No,Sun,Dinner,3,3.45,Douglas Tucker,4478071379779230
Sun4458,21.01,3.50,Male,No,Sun,Dinner,3,7.00,Travis Walters,6011812112971322
Sun5260,23.68,3.31,Male,No,Sun,Dinner,2,11.84,Nathaniel Harris,4676137647685994

In [ ]:
df.loc[['Sun2959', 'Sun4608']]

,total_bill,tip,sex,smoker,day,time,size,price_per_person,Payer Name,CC Number
Payment ID,,,,,,,,,,
Sun2959,16.99,1.01,Female,No,Sun,Dinner,2,8.49,Christy Cunningham,3560325168603410
Sun4608,10.34,1.66,Male,No,Sun,Dinner,3,3.45,Douglas Tucker,4478071379779230

In [ ]:
df.drop('Sun4608', axis = 0)

,total_bill,tip,sex,smoker,day,time,size,price_per_person,Payer Name,CC Number
Payment ID,,,,,,,,,,
Sun2959,16.99,1.01,Female,No,Sun,Dinner,2,8.49,Christy Cunningham,3560325168603410
Sun4458,21.01,3.50,Male,No,Sun,Dinner,3,7.00,Travis Walters,6011812112971322
Sun5260,23.68,3.31,Male,No,Sun,Dinner,2,11.84,Nathaniel Harris,4676137647685994
Sun2251,24.59,3.61,Female,No,Sun,Dinner,4,6.15,Tonya Carter,4832732618637221
Sun9679,25.29,4.71,Male,No,Sun,Dinner,4,6.32,Erik Smith,213140353657882
...,...,...,...,...,...,...,...,...,...,...
Sat2657,29.03,5.92,Male,No,Sat,Dinner,3,9.68,Michael Avila,5296068606052842
Sat1766,27.18,2.00,Female,Yes,Sat,Dinner,2,13.59,Monica Sanders,3506806155565404
Sat3880,22.67,2.00,Male,Yes,Sat,Dinner,2,11.34,Keith Wong,6011891618747196
Sat17,17.82,1.75,Male,No,Sat,Dinner,2,8.91,Dennis Dixon,4375220550950
Thur672,18.78,3.00,Female,No,Thur,Dinner,2,9.39,Michelle Hardin,3511451626698139

In [ ]:
df = df.drop('Sun4608', axis = 0)

In [ ]:
# Incert new row in the DataFrame

one_row = df.iloc[1]

In [ ]:
one_row

total_bill                     21.01
tip                              3.5
sex                             Male
smoker                            No
day                              Sun
time                          Dinner
size                               3
price_per_person                 7.0
Payer Name            Travis Walters
CC Number           6011812112971322
Name: Sun4458, dtype: object

In [ ]:
df.shape

(243, 10)

In [ ]:
df = df.append(one_row)

<ipython-input-75-216f1381fa81>:1: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df = df.append(one_row)

In [ ]:
df.shape

(244, 10)

# **Conditional Filtering**

In [ ]:
import numpy as np
import pandas as pd

In [ ]:
df = pd.read_csv("https://raw.githubusercontent.com/cypherkrish/PythonDataScience/main/Data/tips.csv")

In [ ]:
df.head()

,total_bill,tip,sex,smoker,day,time,size,price_per_person,Payer Name,CC Number,Payment ID
0,16.99,1.01,Female,No,Sun,Dinner,2,8.49,Christy Cunningham,3560325168603410,Sun2959
1,10.34,1.66,Male,No,Sun,Dinner,3,3.45,Douglas Tucker,4478071379779230,Sun4608
2,21.01,3.50,Male,No,Sun,Dinner,3,7.00,Travis Walters,6011812112971322,Sun4458
3,23.68,3.31,Male,No,Sun,Dinner,2,11.84,Nathaniel Harris,4676137647685994,Sun5260
4,24.59,3.61,Female,No,Sun,Dinner,4,6.15,Tonya Carter,4832732618637221,Sun2251

In [ ]:
df['total_bill']

0      16.99
1      10.34
2      21.01
3      23.68
4      24.59
       ...
239    29.03
240    27.18
241    22.67
242    17.82
243    18.78
Name: total_bill, Length: 244, dtype: float64

In [ ]:
df['total_bill'] > 40

0      False
1      False
2      False
3      False
4      False
       ...
239    False
240    False
241    False
242    False
243    False
Name: total_bill, Length: 244, dtype: bool

In [ ]:
bool_series = df['total_bill'] > 40

In [ ]:
df[bool_series]

,total_bill,tip,sex,smoker,day,time,size,price_per_person,Payer Name,CC Number,Payment ID
59,48.27,6.73,Male,No,Sat,Dinner,4,12.07,Brian Ortiz,6596453823950595,Sat8139
95,40.17,4.73,Male,Yes,Fri,Dinner,4,10.04,Aaron Bentley,180026611638690,Fri9628
102,44.30,2.50,Female,Yes,Sat,Dinner,3,14.77,Heather Cohen,379771118886604,Sat6240
142,41.19,5.00,Male,No,Thur,Lunch,5,8.24,Eric Andrews,4356531761046453,Thur3621
156,48.17,5.00,Male,No,Sun,Dinner,6,8.03,Ryan Gonzales,3523151482063321,Sun7518
170,50.81,10.00,Male,Yes,Sat,Dinner,3,16.94,Gregory Clark,5473850968388236,Sat1954
182,45.35,3.50,Male,Yes,Sun,Dinner,3,15.12,Jose Parsons,4112207559459910,Sun2337
184,40.55,3.00,Male,Yes,Sun,Dinner,2,20.27,Stephen Cox,3547798222044029,Sun5140
197,43.11,5.00,Female,Yes,Thur,Lunch,4,10.78,Brooke Soto,5544902205760175,Thur9313
212,48.33,9.00,Male,No,Sat,Dinner,4,12.08,Alex Williamson,676218815212,Sat4590

In [ ]:
# THis can ne dnne like this as well

df[df['total_bill'] > 40]

,total_bill,tip,sex,smoker,day,time,size,price_per_person,Payer Name,CC Number,Payment ID
59,48.27,6.73,Male,No,Sat,Dinner,4,12.07,Brian Ortiz,6596453823950595,Sat8139
95,40.17,4.73,Male,Yes,Fri,Dinner,4,10.04,Aaron Bentley,180026611638690,Fri9628
102,44.30,2.50,Female,Yes,Sat,Dinner,3,14.77,Heather Cohen,379771118886604,Sat6240
142,41.19,5.00,Male,No,Thur,Lunch,5,8.24,Eric Andrews,4356531761046453,Thur3621
156,48.17,5.00,Male,No,Sun,Dinner,6,8.03,Ryan Gonzales,3523151482063321,Sun7518
170,50.81,10.00,Male,Yes,Sat,Dinner,3,16.94,Gregory Clark,5473850968388236,Sat1954
182,45.35,3.50,Male,Yes,Sun,Dinner,3,15.12,Jose Parsons,4112207559459910,Sun2337
184,40.55,3.00,Male,Yes,Sun,Dinner,2,20.27,Stephen Cox,3547798222044029,Sun5140
197,43.11,5.00,Female,Yes,Thur,Lunch,4,10.78,Brooke Soto,5544902205760175,Thur9313
212,48.33,9.00,Male,No,Sat,Dinner,4,12.08,Alex Williamson,676218815212,Sat4590

In [ ]:
df[df['sex'] == 'Male']

,total_bill,tip,sex,smoker,day,time,size,price_per_person,Payer Name,CC Number,Payment ID
1,10.34,1.66,Male,No,Sun,Dinner,3,3.45,Douglas Tucker,4478071379779230,Sun4608
2,21.01,3.50,Male,No,Sun,Dinner,3,7.00,Travis Walters,6011812112971322,Sun4458
3,23.68,3.31,Male,No,Sun,Dinner,2,11.84,Nathaniel Harris,4676137647685994,Sun5260
5,25.29,4.71,Male,No,Sun,Dinner,4,6.32,Erik Smith,213140353657882,Sun9679
6,8.77,2.00,Male,No,Sun,Dinner,2,4.38,Kristopher Johnson,2223727524230344,Sun5985
...,...,...,...,...,...,...,...,...,...,...,...
236,12.60,1.00,Male,Yes,Sat,Dinner,2,6.30,Matthew Myers,3543676378973965,Sat5032
237,32.83,1.17,Male,Yes,Sat,Dinner,2,16.42,Thomas Brown,4284722681265508,Sat2929
239,29.03,5.92,Male,No,Sat,Dinner,3,9.68,Michael Avila,5296068606052842,Sat2657
241,22.67,2.00,Male,Yes,Sat,Dinner,2,11.34,Keith Wong,6011891618747196,Sat3880
242,17.82,1.75,Male,No,Sat,Dinner,2,8.91,Dennis Dixon,4375220550950,Sat17

In [ ]:
df[df['sex'] == 'Female']

,total_bill,tip,sex,smoker,day,time,size,price_per_person,Payer Name,CC Number,Payment ID
0,16.99,1.01,Female,No,Sun,Dinner,2,8.49,Christy Cunningham,3560325168603410,Sun2959
4,24.59,3.61,Female,No,Sun,Dinner,4,6.15,Tonya Carter,4832732618637221,Sun2251
11,35.26,5.00,Female,No,Sun,Dinner,4,8.82,Diane Macias,4577817359320969,Sun6686
14,14.83,3.02,Female,No,Sun,Dinner,2,7.42,Vanessa Jones,30016702287574,Sun3848
16,10.33,1.67,Female,No,Sun,Dinner,3,3.44,Elizabeth Foster,4240025044626033,Sun9715
...,...,...,...,...,...,...,...,...,...,...,...
226,10.09,2.00,Female,Yes,Fri,Lunch,2,5.04,Ruth Weiss,5268689490381635,Fri6359
229,22.12,2.88,Female,Yes,Sat,Dinner,2,11.06,Jennifer Russell,4793003293608,Sat3943
238,35.83,4.67,Female,No,Sat,Dinner,3,11.94,Kimberly Crane,676184013727,Sat9777
240,27.18,2.00,Female,Yes,Sat,Dinner,2,13.59,Monica Sanders,3506806155565404,Sat1766
243,18.78,3.00,Female,No,Thur,Dinner,2,9.39,Michelle Hardin,3511451626698139,Thur672

In [ ]:
df[df['size'] > 3]

,total_bill,tip,sex,smoker,day,time,size,price_per_person,Payer Name,CC Number,Payment ID
4,24.59,3.61,Female,No,Sun,Dinner,4,6.15,Tonya Carter,4832732618637221,Sun2251
5,25.29,4.71,Male,No,Sun,Dinner,4,6.32,Erik Smith,213140353657882,Sun9679
7,26.88,3.12,Male,No,Sun,Dinner,4,6.72,Robert Buck,3514785077705092,Sun8157
11,35.26,5.00,Female,No,Sun,Dinner,4,8.82,Diane Macias,4577817359320969,Sun6686
13,18.43,3.00,Male,No,Sun,Dinner,4,4.61,Joshua Jones,6011163105616890,Sun2971
23,39.42,7.58,Male,No,Sat,Dinner,4,9.86,Lance Peterson,3542584061609808,Sat239
25,17.81,2.34,Male,No,Sat,Dinner,4,4.45,Robert Perkins,30502930499388,Sat907
31,18.35,2.50,Male,No,Sat,Dinner,4,4.59,Danny Santiago,630415546013,Sat4947
33,20.69,2.45,Female,No,Sat,Dinner,4,5.17,Amber Francis,377742985258914,Sat6649
44,30.40,5.60,Male,No,Sun,Dinner,4,7.60,Todd Cooper,503846761263,Sun2274
47,32.40,6.00,Male,No,Sun,Dinner,4,8.10,James Barnes,3552002592874186,Sun9677
52,34.81,5.20,Female,No,Sun,Dinner,4,8.70,Emily Daniel,4291280793094374,Sun6165
54,25.56,4.34,Male,No,Sun,Dinner,4,6.39,Ronald Owens,6569607991983380,Sun9470
56,38.01,3.00,Male,Yes,Sat,Dinner,4,9.50,James Christensen DDS,349793629453226,Sat8903
59,48.27,6.73,Male,No,Sat,Dinner,4,12.07,Brian Ortiz,6596453823950595,Sat8139
63,18.29,3.76,Male,Yes,Sat,Dinner,4,4.57,Chad Hart,580171498976,Sat4178
77,27.20,4.00,Male,No,Thur,Lunch,4,6.80,John Davis,30344778738589,Thur4924
85,34.83,5.17,Female,No,Thur,Lunch,4,8.71,Shawna Cook,6011787464177340,Thur7972
95,40.17,4.73,Male,Yes,Fri,Dinner,4,10.04,Aaron Bentley,180026611638690,Fri9628
116,29.93,5.07,Male,No,Sun,Dinner,4,7.48,Shawn Blake,4689079711213722,Sun22
119,24.08,2.92,Female,No,Thur,Lunch,4,6.02,Melanie Jordan,676212062720,Thur8063
125,29.80,4.20,Female,No,Thur,Lunch,6,4.97,Angela Sanchez,503857080488,Thur3948
141,34.30,6.70,Male,No,Thur,Lunch,6,5.72,Steven Carlson,3526515703718508,Thur1025
142,41.19,5.00,Male,No,Thur,Lunch,5,8.24,Eric Andrews,4356531761046453,Thur3621
143,27.05,5.00,Female,No,Thur,Lunch,6,4.51,Regina Jones,4311048695487,Thur6179
153,24.55,2.00,Male,No,Sun,Dinner,4,6.14,Todd Patterson,4416804908942159,Sun8670
154,19.77,2.00,Male,No,Sun,Dinner,4,4.94,James Smith,213169731428229,Sun5814
155,29.85,5.14,Female,No,Sun,Dinner,5,5.97,Madison Wilson,4210875236164664,Sun9176
156,48.17,5.00,Male,No,Sun,Dinner,6,8.03,Ryan Gonzales,3523151482063321,Sun7518
157,25.00,3.75,Female,No,Sun,Dinner,4,6.25,Laura Robles,213158685144262,Sun7015
159,16.49,2.00,Male,No,Sun,Dinner,4,4.12,Christopher Soto,30501814271434,Sun1781
160,21.50,3.50,Male,No,Sun,Dinner,4,5.38,Travis Gonzalez,3527668419764685,Sun245
167,31.71,4.50,Male,No,Sun,Dinner,4,7.93,Michael Lawson,3566285921227119,Sun3719
180,34.65,3.68,Male,Yes,Sun,Dinner,4,8.66,James Hebert DDS,676168737648,Sun7544
183,23.17,6.50,Male,Yes,Sun,Dinner,4,5.79,Dr. Michael James,4718501859162,Sun6059
185,20.69,5.00,Male,No,Sun,Dinner,5,4.14,Joseph Howell,30362407455623,Sun5842
187,30.46,2.00,Male,Yes,Sun,Dinner,5,6.09,David Barrett,4792882899700988,Sun9987
197,43.11,5.00,Female,Yes,Thur,Lunch,4,10.78,Brooke Soto,5544902205760175,Thur9313
204,20.53,4.00,Male,Yes,Thur,Lunch,4,5.13,Scott Kim,3570611756827620,Thur2160
207,38.73,3.00,Male,Yes,Sat,Dinner,4,9.68,Ricky Ramirez,347817964484033,Sat4505
211,25.89,5.16,Male,Yes,Sat,Dinner,4,6.47,Christopher Li,6011962464150569,Sat6735
212,48.33,9.00,Male,No,Sat,Dinner,4,12.08,Alex Williamson,676218815212,Sat4590
216,28.15,3.00,Male,Yes,Sat,Dinner,5,5.63,Shawn Barnett PhD,4590982568244,Sat7320
219,30.14,3.09,Female,Yes,Sat,Dinner,4,7.54,Shelby House,502097403252,Sat8863
227,20.45,3.00,Male,No,Sat,Dinner,4,5.11,Robert Bradley,213141668145910,Sat4319
230,24.01,2.00,Male,Yes,Sat,Dinner,4,6.00,Michael Osborne,4258682154026,Sat7872

In [ ]:
# Working with multiple conditions

In [ ]:
df[(df['total_bill'] > 30) & (df['sex'] == 'Male')]

,total_bill,tip,sex,smoker,day,time,size,price_per_person,Payer Name,CC Number,Payment ID
23,39.42,7.58,Male,No,Sat,Dinner,4,9.86,Lance Peterson,3542584061609808,Sat239
39,31.27,5.00,Male,No,Sat,Dinner,3,10.42,Mr. Brandon Berry,6011525851069856,Sat6373
44,30.40,5.60,Male,No,Sun,Dinner,4,7.60,Todd Cooper,503846761263,Sun2274
47,32.40,6.00,Male,No,Sun,Dinner,4,8.10,James Barnes,3552002592874186,Sun9677
56,38.01,3.00,Male,Yes,Sat,Dinner,4,9.50,James Christensen DDS,349793629453226,Sat8903
59,48.27,6.73,Male,No,Sat,Dinner,4,12.07,Brian Ortiz,6596453823950595,Sat8139
83,32.68,5.00,Male,Yes,Thur,Lunch,2,16.34,Daniel Murphy,5356177501009133,Thur8801
95,40.17,4.73,Male,Yes,Fri,Dinner,4,10.04,Aaron Bentley,180026611638690,Fri9628
112,38.07,4.00,Male,No,Sun,Dinner,3,12.69,Jeff Lopez,3572865915176463,Sun591
141,34.30,6.70,Male,No,Thur,Lunch,6,5.72,Steven Carlson,3526515703718508,Thur1025
142,41.19,5.00,Male,No,Thur,Lunch,5,8.24,Eric Andrews,4356531761046453,Thur3621
156,48.17,5.00,Male,No,Sun,Dinner,6,8.03,Ryan Gonzales,3523151482063321,Sun7518
167,31.71,4.50,Male,No,Sun,Dinner,4,7.93,Michael Lawson,3566285921227119,Sun3719
170,50.81,10.00,Male,Yes,Sat,Dinner,3,16.94,Gregory Clark,5473850968388236,Sat1954
173,31.85,3.18,Male,Yes,Sun,Dinner,2,15.92,Scott Perez,3577115550328507,Sun9335
175,32.90,3.11,Male,Yes,Sun,Dinner,2,16.45,Nathan Reynolds,370307040837149,Sun5109
179,34.63,3.55,Male,Yes,Sun,Dinner,2,17.32,Brian Bailey,346656312114848,Sun9851
180,34.65,3.68,Male,Yes,Sun,Dinner,4,8.66,James Hebert DDS,676168737648,Sun7544
182,45.35,3.50,Male,Yes,Sun,Dinner,3,15.12,Jose Parsons,4112207559459910,Sun2337
184,40.55,3.00,Male,Yes,Sun,Dinner,2,20.27,Stephen Cox,3547798222044029,Sun5140
187,30.46,2.00,Male,Yes,Sun,Dinner,5,6.09,David Barrett,4792882899700988,Sun9987
207,38.73,3.00,Male,Yes,Sat,Dinner,4,9.68,Ricky Ramirez,347817964484033,Sat4505
210,30.06,2.00,Male,Yes,Sat,Dinner,3,10.02,Shawn Mendoza,30184049218122,Sat8361
212,48.33,9.00,Male,No,Sat,Dinner,4,12.08,Alex Williamson,676218815212,Sat4590
237,32.83,1.17,Male,Yes,Sat,Dinner,2,16.42,Thomas Brown,4284722681265508,Sat2929

In [ ]:
df[(df['total_bill'] > 30) | (df['sex'] == 'Male')]

,total_bill,tip,sex,smoker,day,time,size,price_per_person,Payer Name,CC Number,Payment ID
1,10.34,1.66,Male,No,Sun,Dinner,3,3.45,Douglas Tucker,4478071379779230,Sun4608
2,21.01,3.50,Male,No,Sun,Dinner,3,7.00,Travis Walters,6011812112971322,Sun4458
3,23.68,3.31,Male,No,Sun,Dinner,2,11.84,Nathaniel Harris,4676137647685994,Sun5260
5,25.29,4.71,Male,No,Sun,Dinner,4,6.32,Erik Smith,213140353657882,Sun9679
6,8.77,2.00,Male,No,Sun,Dinner,2,4.38,Kristopher Johnson,2223727524230344,Sun5985
...,...,...,...,...,...,...,...,...,...,...,...
237,32.83,1.17,Male,Yes,Sat,Dinner,2,16.42,Thomas Brown,4284722681265508,Sat2929
238,35.83,4.67,Female,No,Sat,Dinner,3,11.94,Kimberly Crane,676184013727,Sat9777
239,29.03,5.92,Male,No,Sat,Dinner,3,9.68,Michael Avila,5296068606052842,Sat2657
241,22.67,2.00,Male,Yes,Sat,Dinner,2,11.34,Keith Wong,6011891618747196,Sat3880
242,17.82,1.75,Male,No,Sat,Dinner,2,8.91,Dennis Dixon,4375220550950,Sat17

In [ ]:
df.head()

,total_bill,tip,sex,smoker,day,time,size,price_per_person,Payer Name,CC Number,Payment ID
0,16.99,1.01,Female,No,Sun,Dinner,2,8.49,Christy Cunningham,3560325168603410,Sun2959
1,10.34,1.66,Male,No,Sun,Dinner,3,3.45,Douglas Tucker,4478071379779230,Sun4608
2,21.01,3.50,Male,No,Sun,Dinner,3,7.00,Travis Walters,6011812112971322,Sun4458
3,23.68,3.31,Male,No,Sun,Dinner,2,11.84,Nathaniel Harris,4676137647685994,Sun5260
4,24.59,3.61,Female,No,Sun,Dinner,4,6.15,Tonya Carter,4832732618637221,Sun2251

In [ ]:
df[(df['day'] ==  'Sun') | (df['day'] == 'Sat') | (df['day'] == 'Fri')]

,total_bill,tip,sex,smoker,day,time,size,price_per_person,Payer Name,CC Number,Payment ID
0,16.99,1.01,Female,No,Sun,Dinner,2,8.49,Christy Cunningham,3560325168603410,Sun2959
1,10.34,1.66,Male,No,Sun,Dinner,3,3.45,Douglas Tucker,4478071379779230,Sun4608
2,21.01,3.50,Male,No,Sun,Dinner,3,7.00,Travis Walters,6011812112971322,Sun4458
3,23.68,3.31,Male,No,Sun,Dinner,2,11.84,Nathaniel Harris,4676137647685994,Sun5260
4,24.59,3.61,Female,No,Sun,Dinner,4,6.15,Tonya Carter,4832732618637221,Sun2251
...,...,...,...,...,...,...,...,...,...,...,...
238,35.83,4.67,Female,No,Sat,Dinner,3,11.94,Kimberly Crane,676184013727,Sat9777
239,29.03,5.92,Male,No,Sat,Dinner,3,9.68,Michael Avila,5296068606052842,Sat2657
240,27.18,2.00,Female,Yes,Sat,Dinner,2,13.59,Monica Sanders,3506806155565404,Sat1766
241,22.67,2.00,Male,Yes,Sat,Dinner,2,11.34,Keith Wong,6011891618747196,Sat3880
242,17.82,1.75,Male,No,Sat,Dinner,2,8.91,Dennis Dixon,4375220550950,Sat17

In [ ]:
#This is simplified with this below statement

options = ['Sat', 'Fri', 'Sun']
df[df['day'].isin(options)]

,total_bill,tip,sex,smoker,day,time,size,price_per_person,Payer Name,CC Number,Payment ID
0,16.99,1.01,Female,No,Sun,Dinner,2,8.49,Christy Cunningham,3560325168603410,Sun2959
1,10.34,1.66,Male,No,Sun,Dinner,3,3.45,Douglas Tucker,4478071379779230,Sun4608
2,21.01,3.50,Male,No,Sun,Dinner,3,7.00,Travis Walters,6011812112971322,Sun4458
3,23.68,3.31,Male,No,Sun,Dinner,2,11.84,Nathaniel Harris,4676137647685994,Sun5260
4,24.59,3.61,Female,No,Sun,Dinner,4,6.15,Tonya Carter,4832732618637221,Sun2251
...,...,...,...,...,...,...,...,...,...,...,...
238,35.83,4.67,Female,No,Sat,Dinner,3,11.94,Kimberly Crane,676184013727,Sat9777
239,29.03,5.92,Male,No,Sat,Dinner,3,9.68,Michael Avila,5296068606052842,Sat2657
240,27.18,2.00,Female,Yes,Sat,Dinner,2,13.59,Monica Sanders,3506806155565404,Sat1766
241,22.67,2.00,Male,Yes,Sat,Dinner,2,11.34,Keith Wong,6011891618747196,Sat3880
242,17.82,1.75,Male,No,Sat,Dinner,2,8.91,Dennis Dixon,4375220550950,Sat17

#**Pandas Usefull Methods**

In [ ]:
import pandas as pd
import numpy as np

In [ ]:
df = pd.read_csv("https://raw.githubusercontent.com/cypherkrish/PythonDataScience/main/Data/tips.csv")

In [ ]:
df.head()

,total_bill,tip,sex,smoker,day,time,size,price_per_person,Payer Name,CC Number,Payment ID
0,16.99,1.01,Female,No,Sun,Dinner,2,8.49,Christy Cunningham,3560325168603410,Sun2959
1,10.34,1.66,Male,No,Sun,Dinner,3,3.45,Douglas Tucker,4478071379779230,Sun4608
2,21.01,3.50,Male,No,Sun,Dinner,3,7.00,Travis Walters,6011812112971322,Sun4458
3,23.68,3.31,Male,No,Sun,Dinner,2,11.84,Nathaniel Harris,4676137647685994,Sun5260
4,24.59,3.61,Female,No,Sun,Dinner,4,6.15,Tonya Carter,4832732618637221,Sun2251

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 244 entries, 0 to 243
Data columns (total 11 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   total_bill        244 non-null    float64
 1   tip               244 non-null    float64
 2   sex               244 non-null    object
 3   smoker            244 non-null    object
 4   day               244 non-null    object
 5   time              244 non-null    object
 6   size              244 non-null    int64
 7   price_per_person  244 non-null    float64
 8   Payer Name        244 non-null    object
 9   CC Number         244 non-null    int64
 10  Payment ID        244 non-null    object
dtypes: float64(3), int64(2), object(6)
memory usage: 21.1+ KB

In [ ]:
str(123456789)[4:-1]   # to slice the string object. Concerted the int to string here

'5678'

In [ ]:
def last_four(num):
  return str(num)[-4:]  #Returns last 4 digits of the number

In [ ]:
last_four(123456789)

'6789'

In [ ]:
df['CC Number']

0      3560325168603410
1      4478071379779230
2      6011812112971322
3      4676137647685994
4      4832732618637221
             ...
239    5296068606052842
240    3506806155565404
241    6011891618747196
242       4375220550950
243    3511451626698139
Name: CC Number, Length: 244, dtype: int64

In [ ]:
df['CC Number'].apply(last_four)

0      3410
1      9230
2      1322
3      5994
4      7221
       ...
239    2842
240    5404
241    7196
242    0950
243    8139
Name: CC Number, Length: 244, dtype: object

In [ ]:
df['total_bill'].mean()

19.78594262295082

In [ ]:
def yelp(price):
  if price < 10:
    return '$'
  elif price >= 10 and price < 30:
    return '$$'
  else:
    return '$$$'

In [ ]:
df['yelp'] = df['total_bill'].apply(yelp)

In [ ]:
df['yelp']

0      $$
1      $$
2      $$
3      $$
4      $$
       ..
239    $$
240    $$
241    $$
242    $$
243    $$
Name: yelp, Length: 244, dtype: object

#

```
# This is formatted as code
```

Lambda Functions

In [ ]:
def simple(num):
  return num * 2

In [ ]:
simple(5)

10

In [ ]:
lambda num: num * 2

In [ ]:
df['total_bill'].apply(simple)

0      33.98
1      20.68
2      42.02
3      47.36
4      49.18
       ...
239    58.06
240    54.36
241    45.34
242    35.64
243    37.56
Name: total_bill, Length: 244, dtype: float64

In [ ]:
df['total_bill'].apply(lambda bill: bill * 2)

0      33.98
1      20.68
2      42.02
3      47.36
4      49.18
       ...
239    58.06
240    54.36
241    45.34
242    35.64
243    37.56
Name: total_bill, Length: 244, dtype: float64

In [ ]:
df.head()

,total_bill,tip,sex,smoker,day,time,size,price_per_person,Payer Name,CC Number,Payment ID,yelp
0,16.99,1.01,Female,No,Sun,Dinner,2,8.49,Christy Cunningham,3560325168603410,Sun2959,$$
1,10.34,1.66,Male,No,Sun,Dinner,3,3.45,Douglas Tucker,4478071379779230,Sun4608,$$
2,21.01,3.50,Male,No,Sun,Dinner,3,7.00,Travis Walters,6011812112971322,Sun4458,$$
3,23.68,3.31,Male,No,Sun,Dinner,2,11.84,Nathaniel Harris,4676137647685994,Sun5260,$$
4,24.59,3.61,Female,No,Sun,Dinner,4,6.15,Tonya Carter,4832732618637221,Sun2251,$$

In [ ]:
def quality(total_bill, tip):
  if tip/total_bill > 0.25:
    return "Generous"
  else:
    return "Other"

In [ ]:
quality(21.01, 3.50)

'Other'

In [ ]:
df[['total_bill', 'tip']].apply(lambda df: quality(df['total_bill'], df['tip']), axis = 1)

0      Other
1      Other
2      Other
3      Other
4      Other
       ...
239    Other
240    Other
241    Other
242    Other
243    Other
Length: 244, dtype: object

In [ ]:
df['quality'] = df[['total_bill', 'tip']].apply(lambda df: quality(df['total_bill'], df['tip']), axis = 1)

In [ ]:
df['quality']

0      Other
1      Other
2      Other
3      Other
4      Other
       ...
239    Other
240    Other
241    Other
242    Other
243    Other
Name: quality, Length: 244, dtype: object

## np.vectorizer function for the same functionality

In [ ]:
df['quality'] = np.vectorize(quality)(df['total_bill'], df['tip'])

### Compare the efficiencey between the two statements bold text

In [ ]:
import timeit

In [ ]:
# Write a setup code snippet

setup = '''
import pandas as pd
import numpy as np
df = pd.read_csv("https://raw.githubusercontent.com/cypherkrish/PythonDataScience/main/Data/tips.csv")
def quality(total_bill, tip):
  if tip/total_bill > 0.25:
    return "Generous"
  else:
    return "Other"
'''

In [ ]:
stmt_one = '''
df['quality'] = df[['total_bill', 'tip']].apply(lambda df: quality(df['total_bill'], df['tip']), axis = 1)
'''

In [ ]:
stmt_two = '''
df['quality'] = np.vectorize(quality)(df['total_bill'], df['tip'])
'''

In [ ]:
timeit.timeit(setup=setup, stmt = stmt_one, number = 1000)

3.8149383320001107

In [ ]:
timeit.timeit(setup=setup, stmt = stmt_two, number = 1000)

0.5224620649996723

# **Statistical Methods**

In [ ]:
import pandas as pd
import numpy as np
df = pd.read_csv("https://raw.githubusercontent.com/cypherkrish/PythonDataScience/main/Data/tips.csv")

In [ ]:
df.sort_values('tip')

,total_bill,tip,sex,smoker,day,time,size,price_per_person,Payer Name,CC Number,Payment ID
67,3.07,1.00,Female,Yes,Sat,Dinner,1,3.07,Tiffany Brock,4359488526995267,Sat3455
236,12.60,1.00,Male,Yes,Sat,Dinner,2,6.30,Matthew Myers,3543676378973965,Sat5032
92,5.75,1.00,Female,Yes,Fri,Dinner,2,2.88,Leah Ramirez,3508911676966392,Fri3780
111,7.25,1.00,Female,No,Sat,Dinner,1,7.25,Terri Jones,3559221007826887,Sat4801
0,16.99,1.01,Female,No,Sun,Dinner,2,8.49,Christy Cunningham,3560325168603410,Sun2959
...,...,...,...,...,...,...,...,...,...,...,...
141,34.30,6.70,Male,No,Thur,Lunch,6,5.72,Steven Carlson,3526515703718508,Thur1025
59,48.27,6.73,Male,No,Sat,Dinner,4,12.07,Brian Ortiz,6596453823950595,Sat8139
23,39.42,7.58,Male,No,Sat,Dinner,4,9.86,Lance Peterson,3542584061609808,Sat239
212,48.33,9.00,Male,No,Sat,Dinner,4,12.08,Alex Williamson,676218815212,Sat4590
170,50.81,10.00,Male,Yes,Sat,Dinner,3,16.94,Gregory Clark,5473850968388236,Sat1954

In [ ]:
df.sort_values('tip', ascending = True)

,total_bill,tip,sex,smoker,day,time,size,price_per_person,Payer Name,CC Number,Payment ID
67,3.07,1.00,Female,Yes,Sat,Dinner,1,3.07,Tiffany Brock,4359488526995267,Sat3455
236,12.60,1.00,Male,Yes,Sat,Dinner,2,6.30,Matthew Myers,3543676378973965,Sat5032
92,5.75,1.00,Female,Yes,Fri,Dinner,2,2.88,Leah Ramirez,3508911676966392,Fri3780
111,7.25,1.00,Female,No,Sat,Dinner,1,7.25,Terri Jones,3559221007826887,Sat4801
0,16.99,1.01,Female,No,Sun,Dinner,2,8.49,Christy Cunningham,3560325168603410,Sun2959
...,...,...,...,...,...,...,...,...,...,...,...
141,34.30,6.70,Male,No,Thur,Lunch,6,5.72,Steven Carlson,3526515703718508,Thur1025
59,48.27,6.73,Male,No,Sat,Dinner,4,12.07,Brian Ortiz,6596453823950595,Sat8139
23,39.42,7.58,Male,No,Sat,Dinner,4,9.86,Lance Peterson,3542584061609808,Sat239
212,48.33,9.00,Male,No,Sat,Dinner,4,12.08,Alex Williamson,676218815212,Sat4590
170,50.81,10.00,Male,Yes,Sat,Dinner,3,16.94,Gregory Clark,5473850968388236,Sat1954

In [ ]:
df.sort_values(['tip', 'size'])

,total_bill,tip,sex,smoker,day,time,size,price_per_person,Payer Name,CC Number,Payment ID
67,3.07,1.00,Female,Yes,Sat,Dinner,1,3.07,Tiffany Brock,4359488526995267,Sat3455
111,7.25,1.00,Female,No,Sat,Dinner,1,7.25,Terri Jones,3559221007826887,Sat4801
92,5.75,1.00,Female,Yes,Fri,Dinner,2,2.88,Leah Ramirez,3508911676966392,Fri3780
236,12.60,1.00,Male,Yes,Sat,Dinner,2,6.30,Matthew Myers,3543676378973965,Sat5032
0,16.99,1.01,Female,No,Sun,Dinner,2,8.49,Christy Cunningham,3560325168603410,Sun2959
...,...,...,...,...,...,...,...,...,...,...,...
141,34.30,6.70,Male,No,Thur,Lunch,6,5.72,Steven Carlson,3526515703718508,Thur1025
59,48.27,6.73,Male,No,Sat,Dinner,4,12.07,Brian Ortiz,6596453823950595,Sat8139
23,39.42,7.58,Male,No,Sat,Dinner,4,9.86,Lance Peterson,3542584061609808,Sat239
212,48.33,9.00,Male,No,Sat,Dinner,4,12.08,Alex Williamson,676218815212,Sat4590
170,50.81,10.00,Male,Yes,Sat,Dinner,3,16.94,Gregory Clark,5473850968388236,Sat1954

In [ ]:
df['total_bill'].max()

50.81

In [ ]:
df['total_bill'].idxmax() # Gives the index value of the max column value

170

In [ ]:
df.iloc[170]

total_bill                     50.81
tip                             10.0
sex                             Male
smoker                           Yes
day                              Sat
time                          Dinner
size                               3
price_per_person               16.94
Payer Name             Gregory Clark
CC Number           5473850968388236
Payment ID                   Sat1954
Name: 170, dtype: object

In [ ]:
df['total_bill'].min()

3.07

In [ ]:
df['total_bill'].idxmin()

67

In [ ]:
df.iloc[67]

total_bill                      3.07
tip                              1.0
sex                           Female
smoker                           Yes
day                              Sat
time                          Dinner
size                               1
price_per_person                3.07
Payer Name             Tiffany Brock
CC Number           4359488526995267
Payment ID                   Sat3455
Name: 67, dtype: object

In [ ]:
df.corr()

<ipython-input-12-2f6f6606aa2c>:1: FutureWarning: The default value of numeric_only in DataFrame.corr is deprecated. In a future version, it will default to False. Select only valid columns or specify the value of numeric_only to silence this warning.
  df.corr()

                  total_bill       tip      size  price_per_person  CC Number
total_bill          1.000000  0.675734  0.598315          0.647554   0.104576
tip                 0.675734  1.000000  0.489299          0.347405   0.110857
size                0.598315  0.489299  1.000000         -0.175359  -0.030239
price_per_person    0.647554  0.347405 -0.175359          1.000000   0.135240
CC Number           0.104576  0.110857 -0.030239          0.135240   1.000000

In [ ]:
df.head()

,total_bill,tip,sex,smoker,day,time,size,price_per_person,Payer Name,CC Number,Payment ID
0,16.99,1.01,Female,No,Sun,Dinner,2,8.49,Christy Cunningham,3560325168603410,Sun2959
1,10.34,1.66,Male,No,Sun,Dinner,3,3.45,Douglas Tucker,4478071379779230,Sun4608
2,21.01,3.50,Male,No,Sun,Dinner,3,7.00,Travis Walters,6011812112971322,Sun4458
3,23.68,3.31,Male,No,Sun,Dinner,2,11.84,Nathaniel Harris,4676137647685994,Sun5260
4,24.59,3.61,Female,No,Sun,Dinner,4,6.15,Tonya Carter,4832732618637221,Sun2251

In [ ]:
df['sex'].value_counts()

Male      157
Female     87
Name: sex, dtype: int64

In [ ]:
df['day'].unique()

array(['Sun', 'Sat', 'Thur', 'Fri'], dtype=object)

In [ ]:
df['day'].nunique()

4

In [ ]:
df['day'].value_counts()

Sat     87
Sun     76
Thur    62
Fri     19
Name: day, dtype: int64

Replace in DataFrame column values

In [ ]:
df.head()

,total_bill,tip,sex,smoker,day,time,size,price_per_person,Payer Name,CC Number,Payment ID
0,16.99,1.01,Female,No,Sun,Dinner,2,8.49,Christy Cunningham,3560325168603410,Sun2959
1,10.34,1.66,Male,No,Sun,Dinner,3,3.45,Douglas Tucker,4478071379779230,Sun4608
2,21.01,3.50,Male,No,Sun,Dinner,3,7.00,Travis Walters,6011812112971322,Sun4458
3,23.68,3.31,Male,No,Sun,Dinner,2,11.84,Nathaniel Harris,4676137647685994,Sun5260
4,24.59,3.61,Female,No,Sun,Dinner,4,6.15,Tonya Carter,4832732618637221,Sun2251

In [ ]:
df['sex'].replace('Female', 'F')

0         F
1      Male
2      Male
3      Male
4         F
       ...
239    Male
240       F
241    Male
242    Male
243       F
Name: sex, Length: 244, dtype: object

In [ ]:
df['sex'].replace('Male', 'M')

0      Female
1           M
2           M
3           M
4      Female
        ...
239         M
240    Female
241         M
242         M
243    Female
Name: sex, Length: 244, dtype: object

In [ ]:
df['sex'].replace(['Female', 'Male'], ['F', 'M'])

0      F
1      M
2      M
3      M
4      F
      ..
239    M
240    F
241    M
242    M
243    F
Name: sex, Length: 244, dtype: object

**Map functions**

In [ ]:
mymap = {'Female': 'F', 'Male': 'M'}

In [ ]:
df['sex'].map(mymap)

0      F
1      M
2      M
3      M
4      F
      ..
239    M
240    F
241    M
242    M
243    F
Name: sex, Length: 244, dtype: object

In [ ]:
sample_df = pd.DataFrame([1, 2, 2], ['a', 'b', 'c'])

In [ ]:
sample_df

   0
a  1
b  2
c  2

In [ ]:
sample_df.duplicated()

a    False
b    False
c     True
dtype: bool

In [ ]:
sample_df1 = pd.DataFrame([1, 2, 2,2], ['a', 'b', 'c','c'])

In [ ]:
sample_df1.duplicated()

a    False
b    False
c     True
c     True
dtype: bool

In [ ]:
df['total_bill'].between(10, 20, inclusive = True)

<ipython-input-39-c512bbba25e8>:1: FutureWarning: Boolean inputs to the `inclusive` argument are deprecated in favour of `both` or `neither`.
  df['total_bill'].between(10, 20, inclusive = True)

0       True
1       True
2      False
3      False
4      False
       ...
239    False
240    False
241    False
242     True
243     True
Name: total_bill, Length: 244, dtype: bool

In [ ]:
df.nlargest(10 ,'tip')

,total_bill,tip,sex,smoker,day,time,size,price_per_person,Payer Name,CC Number,Payment ID
170,50.81,10.00,Male,Yes,Sat,Dinner,3,16.94,Gregory Clark,5473850968388236,Sat1954
212,48.33,9.00,Male,No,Sat,Dinner,4,12.08,Alex Williamson,676218815212,Sat4590
23,39.42,7.58,Male,No,Sat,Dinner,4,9.86,Lance Peterson,3542584061609808,Sat239
59,48.27,6.73,Male,No,Sat,Dinner,4,12.07,Brian Ortiz,6596453823950595,Sat8139
141,34.30,6.70,Male,No,Thur,Lunch,6,5.72,Steven Carlson,3526515703718508,Thur1025
183,23.17,6.50,Male,Yes,Sun,Dinner,4,5.79,Dr. Michael James,4718501859162,Sun6059
214,28.17,6.50,Female,Yes,Sat,Dinner,3,9.39,Marissa Jackson,4922302538691962,Sat3374
47,32.40,6.00,Male,No,Sun,Dinner,4,8.10,James Barnes,3552002592874186,Sun9677
239,29.03,5.92,Male,No,Sat,Dinner,3,9.68,Michael Avila,5296068606052842,Sat2657
88,24.71,5.85,Male,No,Thur,Lunch,2,12.36,Roger Taylor,4410248629955,Thur9003

In [ ]:
df.sort_values('tip', ascending = False).iloc[0:2]

,total_bill,tip,sex,smoker,day,time,size,price_per_person,Payer Name,CC Number,Payment ID
170,50.81,10.0,Male,Yes,Sat,Dinner,3,16.94,Gregory Clark,5473850968388236,Sat1954
212,48.33,9.0,Male,No,Sat,Dinner,4,12.08,Alex Williamson,676218815212,Sat4590

In [ ]:
df.sort_values('tip', ascending = True).iloc[0:2]

,total_bill,tip,sex,smoker,day,time,size,price_per_person,Payer Name,CC Number,Payment ID
67,3.07,1.0,Female,Yes,Sat,Dinner,1,3.07,Tiffany Brock,4359488526995267,Sat3455
236,12.60,1.0,Male,Yes,Sat,Dinner,2,6.30,Matthew Myers,3543676378973965,Sat5032

In [ ]:
df.sample(5)

,total_bill,tip,sex,smoker,day,time,size,price_per_person,Payer Name,CC Number,Payment ID
214,28.17,6.50,Female,Yes,Sat,Dinner,3,9.39,Marissa Jackson,4922302538691962,Sat3374
209,12.76,2.23,Female,Yes,Sat,Dinner,2,6.38,Sarah Cunningham,341876516331163,Sat1274
43,9.68,1.32,Male,No,Sun,Dinner,2,4.84,Christopher Spears,4387671121369212,Sun3279
131,20.27,2.83,Female,No,Thur,Lunch,2,10.14,Ashley Burke,5394652998970066,Thur9005
109,14.31,4.00,Female,Yes,Sat,Dinner,2,7.16,Amanda Anderson,375638820334211,Sat2614

In [ ]:
df.sample(frac = 0.2)

Empty DataFrame
Columns: [total_bill, tip, sex, smoker, day, time, size, price_per_person, Payer Name, CC Number, Payment ID]
Index: []

## Missing data

In [ ]:
import pandas as pd
import numpy as np

In [ ]:
pd.NA

In [ ]:
np.nan

nan

In [ ]:
pd.NaT

NaT

In [ ]:
np.nan == np.nan

False

In [ ]:
np.nan is np.nan

True

In [ ]:
myvar = np.nan

In [ ]:
myvar is np.nan

True

In [ ]:
df = pd.read_csv("https://raw.githubusercontent.com/cypherkrish/PythonDataScience/main/Data/movie_scores.csv")

In [ ]:
df

  first_name last_name   age  sex  pre_movie_score  post_movie_score
0        Tom     Hanks  63.0    m              8.0              10.0
1        NaN       NaN   NaN  NaN              NaN               NaN
2       Hugh   Jackman  51.0    m              NaN               NaN
3      Oprah   Winfrey  66.0    f              6.0               8.0
4       Emma     Stone  31.0    f              7.0               9.0

In [ ]:
df.isnull()

   first_name  last_name    age    sex  pre_movie_score  post_movie_score
0       False      False  False  False            False             False
1        True       True   True   True             True              True
2       False      False  False  False             True              True
3       False      False  False  False            False             False
4       False      False  False  False            False             False

In [ ]:
df.notnull()

   first_name  last_name    age    sex  pre_movie_score  post_movie_score
0        True       True   True   True             True              True
1       False      False  False  False            False             False
2        True       True   True   True            False             False
3        True       True   True   True             True              True
4        True       True   True   True             True              True

In [ ]:
df[df['pre_movie_score'].notnull()]

  first_name last_name   age sex  pre_movie_score  post_movie_score
0        Tom     Hanks  63.0   m              8.0              10.0
3      Oprah   Winfrey  66.0   f              6.0               8.0
4       Emma     Stone  31.0   f              7.0               9.0

In [ ]:
df[df['pre_movie_score'].isnull()]

  first_name last_name   age  sex  pre_movie_score  post_movie_score
1        NaN       NaN   NaN  NaN              NaN               NaN
2       Hugh   Jackman  51.0    m              NaN               NaN

In [ ]:
df[(df['pre_movie_score'].isnull()) & (df['first_name'].notnull())]

  first_name last_name   age sex  pre_movie_score  post_movie_score
2       Hugh   Jackman  51.0   m              NaN               NaN

In [ ]:
# KEEP DATA
# DROP DATA
# FILL DATA

In [ ]:
df # Keep Data

  first_name last_name   age  sex  pre_movie_score  post_movie_score
0        Tom     Hanks  63.0    m              8.0              10.0
1        NaN       NaN   NaN  NaN              NaN               NaN
2       Hugh   Jackman  51.0    m              NaN               NaN
3      Oprah   Winfrey  66.0    f              6.0               8.0
4       Emma     Stone  31.0    f              7.0               9.0

In [ ]:
help(df.dropna()) # Drop the data

Help on DataFrame in module pandas.core.frame object:

class DataFrame(pandas.core.generic.NDFrame, pandas.core.arraylike.OpsMixin)
 |  DataFrame(data=None, index: 'Axes | None' = None, columns: 'Axes | None' = None, dtype: 'Dtype | None' = None, copy: 'bool | None' = None) -> 'None'
 |
 |  Two-dimensional, size-mutable, potentially heterogeneous tabular data.
 |
 |  Data structure also contains labeled axes (rows and columns).
 |  Arithmetic operations align on both row and column labels. Can be
 |  thought of as a dict-like container for Series objects. The primary
 |  pandas data structure.
 |
 |  Parameters
 |  ----------
 |  data : ndarray (structured or homogeneous), Iterable, dict, or DataFrame
 |      Dict can contain Series, arrays, constants, dataclass or list-like objects. If
 |      data is a dict, column order follows insertion-order. If a dict contains Series
 |      which have an index defined, it is aligned by its index.
 |
 |      .. versionchanged:: 0.25.0
 |         If data is a list of dicts, column order follows insertion-order.
 |
 |  index : Index or array-like
 |      Index to use for resulting frame. Will default to RangeIndex if
 |      no indexing information part of input data and no index provided.
 |  columns : Index or array-like
 |      Column labels to use for resulting frame when data does not have them,
 |      defaulting to RangeIndex(0, 1, 2, ..., n). If data contains column labels,
 |      will perform column selection instead.
 |  dtype : dtype, default None
 |      Data type to force. Only a single dtype is allowed. If None, infer.
 |  copy : bool or None, default None
 |      Copy data from inputs.
 |      For dict data, the default of None behaves like ``copy=True``.  For DataFrame
 |      or 2d ndarray input, the default of None behaves like ``copy=False``.
 |      If data is a dict containing one or more Series (possibly of different dtypes),
 |      ``copy=False`` will ensure that these inputs are not copied.
 |
 |      .. versionchanged:: 1.3.0
 |
 |  See Also
 |  --------
 |  DataFrame.from_records : Constructor from tuples, also record arrays.
 |  DataFrame.from_dict : From dicts of Series, arrays, or dicts.
 |  read_csv : Read a comma-separated values (csv) file into DataFrame.
 |  read_table : Read general delimited file into DataFrame.
 |  read_clipboard : Read text from clipboard into DataFrame.
 |
 |  Notes
 |  -----
 |  Please reference the :ref:`User Guide <basics.dataframe>` for more information.
 |
 |  Examples
 |  --------
 |  Constructing DataFrame from a dictionary.
 |
 |  >>> d = {'col1': [1, 2], 'col2': [3, 4]}
 |  >>> df = pd.DataFrame(data=d)
 |  >>> df
 |     col1  col2
 |  0     1     3
 |  1     2     4
 |
 |  Notice that the inferred dtype is int64.
 |
 |  >>> df.dtypes
 |  col1    int64
 |  col2    int64
 |  dtype: object
 |
 |  To enforce a single dtype:
 |
 |  >>> df = pd.DataFrame(data=d, dtype=np.int8)
 |  >>> df.dtypes
 |  col1    int8
 |  col2    int8
 |  dtype: object
 |
 |  Constructing DataFrame from a dictionary including Series:
 |
 |  >>> d = {'col1': [0, 1, 2, 3], 'col2': pd.Series([2, 3], index=[2, 3])}
 |  >>> pd.DataFrame(data=d, index=[0, 1, 2, 3])
 |     col1  col2
 |  0     0   NaN
 |  1     1   NaN
 |  2     2   2.0
 |  3     3   3.0
 |
 |  Constructing DataFrame from numpy ndarray:
 |
 |  >>> df2 = pd.DataFrame(np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]]),
 |  ...                    columns=['a', 'b', 'c'])
 |  >>> df2
 |     a  b  c
 |  0  1  2  3
 |  1  4  5  6
 |  2  7  8  9
 |
 |  Constructing DataFrame from a numpy ndarray that has labeled columns:
 |
 |  >>> data = np.array([(1, 2, 3), (4, 5, 6), (7, 8, 9)],
 |  ...                 dtype=[("a", "i4"), ("b", "i4"), ("c", "i4")])
 |  >>> df3 = pd.DataFrame(data, columns=['c', 'a'])
 |  ...
 |  >>> df3
 |     c  a
 |  0  3  1
 |  1  6  4
 |  2  9  7
 |
 |  Constructing DataFrame from dataclass:
 |
 |  >>> from dataclasses import make_dataclass
 |  >>> Point = make_dataclass("Point", [("x", int), ("y", int)])
 |  >>> pd.DataFrame([Point(0, 0), Point(0, 3), Point(2, 3)])
 |     x  y
 |  0  0  0
 |  1  0  3
 |  2  2  3
 |
 |  Method resolution order:
 |      DataFrame
 |      pandas.core.generic.NDFrame
 |      pandas.core.base.PandasObject
 |      pandas.core.accessor.DirNamesMixin
 |      pandas.core.indexing.IndexingMixin
 |      pandas.core.arraylike.OpsMixin
 |      builtins.object
 |
 |  Methods defined here:
 |
 |  __dataframe__(self, nan_as_null: 'bool' = False, allow_copy: 'bool' = True) -> 'DataFrameXchg'
 |      Return the dataframe interchange object implementing the interchange protocol.
 |
 |      Parameters
 |      ----------
 |      nan_as_null : bool, default False
 |          Whether to tell the DataFrame to overwrite null values in the data
 |          with ``NaN`` (or ``NaT``).
 |      allow_copy : bool, default True
 |          Whether to allow memory copying when exporting. If set to False
 |          it would cause non-zero-copy exports to fail.
 |
 |      Returns
 |      -------
 |      DataFrame interchange object
 |          The object which consuming library can use to ingress the dataframe.
 |
 |      Notes
 |      -----
 |      Details on the interchange protocol:
 |      https://data-apis.org/dataframe-protocol/latest/index.html
 |
 |      `nan_as_null` currently has no effect; once support for nullable extension
 |      dtypes is added, this value should be propagated to columns.
 |
 |  __divmod__(self, other) -> 'tuple[DataFrame, DataFrame]'
 |
 |  __getitem__(self, key)
 |
 |  __init__(self, data=None, index: 'Axes | None' = None, columns: 'Axes | None' = None, dtype: 'Dtype | None' = None, copy: 'bool | None' = None) -> 'None'
 |      Initialize self.  See help(type(self)) for accurate signature.
 |
 |  __len__(self) -> 'int'
 |      Returns length of info axis, but here we use the index.
 |
 |  __matmul__(self, other: 'AnyArrayLike | DataFrame') -> 'DataFrame | Series'
 |      Matrix multiplication using binary `@` operator in Python>=3.5.
 |
 |  __rdivmod__(self, other) -> 'tuple[DataFrame, DataFrame]'
 |
 |  __repr__(self) -> 'str'
 |      Return a string representation for a particular DataFrame.
 |
 |  __rmatmul__(self, other) -> 'DataFrame'
 |      Matrix multiplication using binary `@` operator in Python>=3.5.
 |
 |  __setitem__(self, key, value)
 |
 |  add(self, other, axis='columns', level=None, fill_value=None)
 |      Get Addition of dataframe and other, element-wise (binary operator `add`).
 |
 |      Equivalent to ``dataframe + other``, but with support to substitute a fill_value
 |      for missing data in one of the inputs. With reverse version, `radd`.
 |
 |      Among flexible wrappers (`add`, `sub`, `mul`, `div`, `mod`, `pow`) to
 |      arithmetic operators: `+`, `-`, `*`, `/`, `//`, `%`, `**`.
 |
 |      Parameters
 |      ----------
 |      other : scalar, sequence, Series, dict or DataFrame
 |          Any single or multiple element data structure, or list-like object.
 |      axis : {0 or 'index', 1 or 'columns'}
 |          Whether to compare by the index (0 or 'index') or columns.
 |          (1 or 'columns'). For Series input, axis to match Series index on.
 |      level : int or label
 |          Broadcast across a level, matching Index values on the
 |          passed MultiIndex level.
 |      fill_value : float or None, default None
 |          Fill existing missing (NaN) values, and any new element needed for
 |          successful DataFrame alignment, with this value before computation.
 |          If data in both corresponding DataFrame locations is missing
 |          the result will be missing.
 |
 |      Returns
 |      -------
 |      DataFrame
 |          Result of the arithmetic operation.
 |
 |      See Also
 |      --------
 |      DataFrame.add : Add DataFrames.
 |      DataFrame.sub : Subtract DataFrames.
 |      DataFrame.mul : Multiply DataFrames.
 |      DataFrame.div : Divide DataFrames (float division).
 |      DataFrame.truediv : Divide DataFrames (float division).
 |      DataFrame.floordiv : Divide DataFrames (integer division).
 |      DataFrame.mod : Calculate modulo (remainder after division).
 |      DataFrame.pow : Calculate exponential power.
 |
 |      Notes
 |      -----
 |      Mismatched indices will be unioned together.
 |
 |      Examples
 |      --------
 |      >>> df = pd.DataFrame({'angles': [0, 3, 4],
 |      ...                    'degrees': [360, 180, 360]},
 |      ...                   index=['circle', 'triangle', 'rectangle'])
 |      >>> df
 |                 angles  degrees
 |      circle          0      360
 |      triangle        3      180
 |      rectangle       4      360
 |
 |      Add a scalar with operator version which return the same
 |      results.
 |
 |      >>> df + 1
 |                 angles  degrees
 |      circle          1      361
 |      triangle        4      181
 |      rectangle       5      361
 |
 |      >>> df.add(1)
 |                 angles  degrees
 |      circle          1      361
 |      triangle        4      181
 |      rectangle       5      361
 |
 |      Divide by constant with reverse version.
 |
 |      >>> df.div(10)
 |                 angles  degrees
 |      circle        0.0     36.0
 |      triangle      0.3     18.0
 |      rectangle     0.4     36.0
 |
 |      >>> df.rdiv(10)
 |                   angles   degrees
 |      circle          inf  0.027778
 |      triangle   3.333333  0.055556
 |      rectangle  2.500000  0.027778
 |
 |      Subtract a list and Series by axis with operator version.
 |
 |      >>> df - [1, 2]
 |                 angles  degrees
 |      circle         -1      358
 |      triangle        2      178
 |      rectangle       3      358
 |
 |      >>> df.sub([1, 2], axis='columns')
 |                 angles  degrees
 |      circle         -1      358
 |      triangle        2      178
 |      rectangle       3      358
 |
 |      >>> df.sub(pd.Series([1, 1, 1], index=['circle', 'triangle', 'rectangle']),
 |      ...        axis='index')
 |                 angles  degrees
 |      circle         -1      359
 |      triangle        2      179
 |      rectangle       3      359
 |
 |      Multiply a dictionary by axis.
 |
 |      >>> df.mul({'angles': 0, 'degrees': 2})
 |                  angles      degrees
 |      circle           0          720
 |      triangle             0      360
 |      rectangle            0      720
 |
 |      >>> df.mul({'circle': 0, 'triangle': 2, 'rectangle': 3}, axis='index')
 |                  angles      degrees
 |      circle               0        0
 |      triangle             6      360
 |      rectangle           12     1080
 |
 |      Multiply a DataFrame of different shape with operator version.
 |
 |      >>> other = pd.DataFrame({'angles': [0, 3, 4]},
 |      ...                      index=['circle', 'triangle', 'rectangle'])
 |      >>> other
 |                 angles
 |      circle          0
 |      triangle        3
 |      rectangle       4
 |
 |      >>> df * other
 |                 angles  degrees
 |      circle          0      NaN
 |      triangle        9      NaN
 |      rectangle      16      NaN
 |
 |      >>> df.mul(other, fill_value=0)
 |                 angles  degrees
 |      circle          0      0.0
 |      triangle        9      0.0
 |      rectangle      16      0.0
 |
 |      Divide by a MultiIndex by level.
 |
 |      >>> df_multindex = pd.DataFrame({'angles': [0, 3, 4, 4, 5, 6],
 |      ...                              'degrees': [360, 180, 360, 360, 540, 720]},
 |      ...                             index=[['A', 'A', 'A', 'B', 'B', 'B'],
 |      ...                                    ['circle', 'triangle', 'rectangle',
 |      ...                                     'square', 'pentagon', 'hexagon']])
 |      >>> df_multindex
 |                   angles  degrees
 |      A circle          0      360
 |        triangle        3      180
 |        rectangle       4      360
 |      B square          4      360
 |        pentagon        5      540
 |        hexagon         6      720
 |
 |      >>> df.div(df_multindex, level=1, fill_value=0)
 |                   angles  degrees
 |      A circle        NaN      1.0
 |        triangle      1.0      1.0
 |        rectangle     1.0      1.0
 |      B square        0.0      0.0
 |        pentagon      0.0      0.0
 |        hexagon       0.0      0.0
 |
 |  agg = aggregate(self, func=None, axis: 'Axis' = 0, *args, **kwargs)
 |
 |  aggregate(self, func=None, axis: 'Axis' = 0, *args, **kwargs)
 |      Aggregate using one or more operations over the specified axis.
 |
 |      Parameters
 |      ----------
 |      func : function, str, list or dict
 |          Function to use for aggregating the data. If a function, must either
 |          work when passed a DataFrame or when passed to DataFrame.apply.
 |
 |          Accepted combinations are:
 |
 |          - function
 |          - string function name
 |          - list of functions and/or function names, e.g. ``[np.sum, 'mean']``
 |          - dict of axis labels -> functions, function names or list of such.
 |      axis : {0 or 'index', 1 or 'columns'}, default 0
 |              If 0 or 'index': apply function to each column.
 |              If 1 or 'columns': apply function to each row.
 |      *args
 |          Positional arguments to pass to `func`.
 |      **kwargs
 |          Keyword arguments to pass to `func`.
 |
 |      Returns
 |      -------
 |      scalar, Series or DataFrame
 |
 |          The return can be:
 |
 |          * scalar : when Series.agg is called with single function
 |          * Series : when DataFrame.agg is called with a single function
 |          * DataFrame : when DataFrame.agg is called with several functions
 |
 |          Return scalar, Series or DataFrame.
 |
 |      The aggregation operations are always performed over an axis, either the
 |      index (default) or the column axis. This behavior is different from
 |      `numpy` aggregation functions (`mean`, `median`, `prod`, `sum`, `std`,
 |      `var`), where the default is to compute the aggregation of the flattened
 |      array, e.g., ``numpy.mean(arr_2d)`` as opposed to
 |      ``numpy.mean(arr_2d, axis=0)``.
 |
 |      `agg` is an alias for `aggregate`. Use the alias.
 |
 |      See Also
 |      --------
 |      DataFrame.apply : Perform any type of operations.
 |      DataFrame.transform : Perform transformation type operations.
 |      core.groupby.GroupBy : Perform operations over groups.
 |      core.resample.Resampler : Perform operations over resampled bins.
 |      core.window.Rolling : Perform operations over rolling window.
 |      core.window.Expanding : Perform operations over expanding window.
 |      core.window.ExponentialMovingWindow : Perform operation over exponential weighted
 |          window.
 |
 |      Notes
 |      -----
 |      `agg` is an alias for `aggregate`. Use the alias.
 |
 |      Functions that mutate the passed object can produce unexpected
 |      behavior or errors and are not supported. See :ref:`gotchas.udf-mutation`
 |      for more details.
 |
 |      A passed user-defined-function will be passed a Series for evaluation.
 |
 |      Examples
 |      --------
 |      >>> df = pd.DataFrame([[1, 2, 3],
 |      ...                    [4, 5, 6],
 |      ...                    [7, 8, 9],
 |      ...                    [np.nan, np.nan, np.nan]],
 |      ...                   columns=['A', 'B', 'C'])
 |
 |      Aggregate these functions over the rows.
 |
 |      >>> df.agg(['sum', 'min'])
 |              A     B     C
 |      sum  12.0  15.0  18.0
 |      min   1.0   2.0   3.0
 |
 |      Different aggregations per column.
 |
 |      >>> df.agg({'A' : ['sum', 'min'], 'B' : ['min', 'max']})
 |              A    B
 |      sum  12.0  NaN
 |      min   1.0  2.0
 |      max   NaN  8.0
 |
 |      Aggregate different functions over the columns and rename the index of the resulting
 |      DataFrame.
 |
 |      >>> df.agg(x=('A', max), y=('B', 'min'), z=('C', np.mean))
 |           A    B    C
 |      x  7.0  NaN  NaN
 |      y  NaN  2.0  NaN
 |      z  NaN  NaN  6.0
 |
 |      Aggregate over the columns.
 |
 |      >>> df.agg("mean", axis="columns")
 |      0    2.0
 |      1    5.0
 |      2    8.0
 |      3    NaN
 |      dtype: float64
 |
 |  align(self, other: 'DataFrame', join: "Literal['outer', 'inner', 'left', 'right']" = 'outer', axis: 'Axis | None' = None, level: 'Level' = None, copy: 'bool' = True, fill_value=None, method: 'FillnaOptions | None' = None, limit: 'int | None' = None, fill_axis: 'Axis' = 0, broadcast_axis: 'Axis | None' = None) -> 'DataFrame'
 |      Align two objects on their axes with the specified join method.
 |
 |      Join method is specified for each axis Index.
 |
 |      Parameters
 |      ----------
 |      other : DataFrame or Series
 |      join : {'outer', 'inner', 'left', 'right'}, default 'outer'
 |      axis : allowed axis of the other object, default None
 |          Align on index (0), columns (1), or both (None).
 |      level : int or level name, default None
 |          Broadcast across a level, matching Index values on the
 |          passed MultiIndex level.
 |      copy : bool, default True
 |          Always returns new objects. If copy=False and no reindexing is
 |          required then original objects are returned.
 |      fill_value : scalar, default np.NaN
 |          Value to use for missing values. Defaults to NaN, but can be any
 |          "compatible" value.
 |      method : {'backfill', 'bfill', 'pad', 'ffill', None}, default None
 |          Method to use for filling holes in reindexed Series:
 |
 |          - pad / ffill: propagate last valid observation forward to next valid.
 |          - backfill / bfill: use NEXT valid observation to fill gap.
 |
 |      limit : int, default None
 |          If method is specified, this is the maximum number of consecutive
 |          NaN values to forward/backward fill. In other words, if there is
 |          a gap with more than this number of consecutive NaNs, it will only
 |          be partially filled. If method is not specified, this is the
 |          maximum number of entries along the entire axis where NaNs will be
 |          filled. Must be greater than 0 if not None.
 |      fill_axis : {0 or 'index', 1 or 'columns'}, default 0
 |          Filling axis, method and limit.
 |      broadcast_axis : {0 or 'index', 1 or 'columns'}, default None
 |          Broadcast values along this axis, if aligning two objects of
 |          different dimensions.
 |
 |      Returns
 |      -------
 |      (left, right) : (DataFrame, type of other)
 |          Aligned objects.
 |
 |      Examples
 |      --------
 |      >>> df = pd.DataFrame(
 |      ...     [[1, 2, 3, 4], [6, 7, 8, 9]], columns=["D", "B", "E", "A"], index=[1, 2]
 |      ... )
 |      >>> other = pd.DataFrame(
 |      ...     [[10, 20, 30, 40], [60, 70, 80, 90], [600, 700, 800, 900]],
 |      ...     columns=["A", "B", "C", "D"],
 |      ...     index=[2, 3, 4],
 |      ... )
 |      >>> df
 |         D  B  E  A
 |      1  1  2  3  4
 |      2  6  7  8  9
 |      >>> other
 |          A    B    C    D
 |      2   10   20   30   40
 |      3   60   70   80   90
 |      4  600  700  800  900
 |
 |      Align on columns:
 |
 |      >>> left, right = df.align(other, join="outer", axis=1)
 |      >>> left
 |         A  B   C  D  E
 |      1  4  2 NaN  1  3
 |      2  9  7 NaN  6  8
 |      >>> right
 |          A    B    C    D   E
 |      2   10   20   30   40 NaN
 |      3   60   70   80   90 NaN
 |      4  600  700  800  900 NaN
 |
 |      We can also align on the index:
 |
 |      >>> left, right = df.align(other, join="outer", axis=0)
 |      >>> left
 |          D    B    E    A
 |      1  1.0  2.0  3.0  4.0
 |      2  6.0  7.0  8.0  9.0
 |      3  NaN  NaN  NaN  NaN
 |      4  NaN  NaN  NaN  NaN
 |      >>> right
 |          A      B      C      D

In [ ]:
df.dropna(thresh=1)

  first_name last_name   age sex  pre_movie_score  post_movie_score
0        Tom     Hanks  63.0   m              8.0              10.0
2       Hugh   Jackman  51.0   m              NaN               NaN
3      Oprah   Winfrey  66.0   f              6.0               8.0
4       Emma     Stone  31.0   f              7.0               9.0

In [ ]:
df.dropna(axis=1)

Empty DataFrame
Columns: []
Index: [0, 1, 2, 3, 4]

In [ ]:
df

  first_name last_name   age  sex  pre_movie_score  post_movie_score
0        Tom     Hanks  63.0    m              8.0              10.0
1        NaN       NaN   NaN  NaN              NaN               NaN
2       Hugh   Jackman  51.0    m              NaN               NaN
3      Oprah   Winfrey  66.0    f              6.0               8.0
4       Emma     Stone  31.0    f              7.0               9.0

In [ ]:
df.dropna(axis = 0)

  first_name last_name   age sex  pre_movie_score  post_movie_score
0        Tom     Hanks  63.0   m              8.0              10.0
3      Oprah   Winfrey  66.0   f              6.0               8.0
4       Emma     Stone  31.0   f              7.0               9.0

In [ ]:
df

  first_name last_name   age  sex  pre_movie_score  post_movie_score
0        Tom     Hanks  63.0    m              8.0              10.0
1        NaN       NaN   NaN  NaN              NaN               NaN
2       Hugh   Jackman  51.0    m              NaN               NaN
3      Oprah   Winfrey  66.0    f              6.0               8.0
4       Emma     Stone  31.0    f              7.0               9.0

In [ ]:
df.dropna(subset = ['last_name'])

  first_name last_name   age sex  pre_movie_score  post_movie_score
0        Tom     Hanks  63.0   m              8.0              10.0
2       Hugh   Jackman  51.0   m              NaN               NaN
3      Oprah   Winfrey  66.0   f              6.0               8.0
4       Emma     Stone  31.0   f              7.0               9.0

In [ ]:
help(df.fillna)

Help on method fillna in module pandas.core.frame:

fillna(value: 'Hashable | Mapping | Series | DataFrame' = None, *, method: 'FillnaOptions | None' = None, axis: 'Axis | None' = None, inplace: 'bool' = False, limit: 'int | None' = None, downcast: 'dict | None' = None) -> 'DataFrame | None' method of pandas.core.frame.DataFrame instance
    Fill NA/NaN values using the specified method.

    Parameters
    ----------
    value : scalar, dict, Series, or DataFrame
        Value to use to fill holes (e.g. 0), alternately a
        dict/Series/DataFrame of values specifying which value to use for
        each index (for a Series) or column (for a DataFrame).  Values not
        in the dict/Series/DataFrame will not be filled. This value cannot
        be a list.
    method : {'backfill', 'bfill', 'pad', 'ffill', None}, default None
        Method to use for filling holes in reindexed Series
        pad / ffill: propagate last valid observation forward to next valid
        backfill / bfill: use next valid observation to fill gap.
    axis : {0 or 'index', 1 or 'columns'}
        Axis along which to fill missing values. For `Series`
        this parameter is unused and defaults to 0.
    inplace : bool, default False
        If True, fill in-place. Note: this will modify any
        other views on this object (e.g., a no-copy slice for a column in a
        DataFrame).
    limit : int, default None
        If method is specified, this is the maximum number of consecutive
        NaN values to forward/backward fill. In other words, if there is
        a gap with more than this number of consecutive NaNs, it will only
        be partially filled. If method is not specified, this is the
        maximum number of entries along the entire axis where NaNs will be
        filled. Must be greater than 0 if not None.
    downcast : dict, default is None
        A dict of item->dtype of what to downcast if possible,
        or the string 'infer' which will try to downcast to an appropriate
        equal type (e.g. float64 to int64 if possible).

    Returns
    -------
    DataFrame or None
        Object with missing values filled or None if ``inplace=True``.

    See Also
    --------
    interpolate : Fill NaN values using interpolation.
    reindex : Conform object to new index.
    asfreq : Convert TimeSeries to specified frequency.

    Examples
    --------
    >>> df = pd.DataFrame([[np.nan, 2, np.nan, 0],
    ...                    [3, 4, np.nan, 1],
    ...                    [np.nan, np.nan, np.nan, np.nan],
    ...                    [np.nan, 3, np.nan, 4]],
    ...                   columns=list("ABCD"))
    >>> df
         A    B   C    D
    0  NaN  2.0 NaN  0.0
    1  3.0  4.0 NaN  1.0
    2  NaN  NaN NaN  NaN
    3  NaN  3.0 NaN  4.0

    Replace all NaN elements with 0s.

    >>> df.fillna(0)
         A    B    C    D
    0  0.0  2.0  0.0  0.0
    1  3.0  4.0  0.0  1.0
    2  0.0  0.0  0.0  0.0
    3  0.0  3.0  0.0  4.0

    We can also propagate non-null values forward or backward.

    >>> df.fillna(method="ffill")
         A    B   C    D
    0  NaN  2.0 NaN  0.0
    1  3.0  4.0 NaN  1.0
    2  3.0  4.0 NaN  1.0
    3  3.0  3.0 NaN  4.0

    Replace all NaN elements in column 'A', 'B', 'C', and 'D', with 0, 1,
    2, and 3 respectively.

    >>> values = {"A": 0, "B": 1, "C": 2, "D": 3}
    >>> df.fillna(value=values)
         A    B    C    D
    0  0.0  2.0  2.0  0.0
    1  3.0  4.0  2.0  1.0
    2  0.0  1.0  2.0  3.0
    3  0.0  3.0  2.0  4.0

    Only replace the first NaN element.

    >>> df.fillna(value=values, limit=1)
         A    B    C    D
    0  0.0  2.0  2.0  0.0
    1  3.0  4.0  NaN  1.0
    2  NaN  1.0  NaN  3.0
    3  NaN  3.0  NaN  4.0

    When filling using a DataFrame, replacement happens along
    the same column names and same indices

    >>> df2 = pd.DataFrame(np.zeros((4, 4)), columns=list("ABCE"))
    >>> df.fillna(df2)
         A    B    C    D
    0  0.0  2.0  0.0  0.0
    1  3.0  4.0  0.0  1.0
    2  0.0  0.0  0.0  NaN
    3  0.0  3.0  0.0  4.0

    Note that column D is not affected since it is not present in df2.

In [ ]:
df.fillna("NEW VALUE!")

,first_name,last_name,age,sex,pre_movie_score,post_movie_score
0,Tom,Hanks,63.0,m,8.0,10.0
1,NEW VALUE!,NEW VALUE!,NEW VALUE!,NEW VALUE!,NEW VALUE!,NEW VALUE!
2,Hugh,Jackman,51.0,m,NEW VALUE!,NEW VALUE!
3,Oprah,Winfrey,66.0,f,6.0,8.0
4,Emma,Stone,31.0,f,7.0,9.0

In [ ]:
df

  first_name last_name   age  sex  pre_movie_score  post_movie_score
0        Tom     Hanks  63.0    m              8.0              10.0
1        NaN       NaN   NaN  NaN              NaN               NaN
2       Hugh   Jackman  51.0    m              NaN               NaN
3      Oprah   Winfrey  66.0    f              6.0               8.0
4       Emma     Stone  31.0    f              7.0               9.0

In [ ]:
df['pre_movie_score'].fillna(0)

0    8.0
1    0.0
2    0.0
3    6.0
4    7.0
Name: pre_movie_score, dtype: float64

In [ ]:
df['pre_movie_score'].mean()

7.0

In [ ]:
df['pre_movie_score'] = df['pre_movie_score'].mean()

In [ ]:
df['pre_movie_score']

0    7.0
1    7.0
2    7.0
3    7.0
4    7.0
Name: pre_movie_score, dtype: float64

In [ ]:
df

  first_name last_name   age  sex  pre_movie_score  post_movie_score
0        Tom     Hanks  63.0    m              7.0              10.0
1        NaN       NaN   NaN  NaN              7.0               NaN
2       Hugh   Jackman  51.0    m              7.0               NaN
3      Oprah   Winfrey  66.0    f              7.0               8.0
4       Emma     Stone  31.0    f              7.0               9.0

In [ ]:
# Interpolation

In [ ]:
airline_tix = {'first': 100, 'business': np.nan, 'economy-plus': 50, 'ecomony':   30}

In [ ]:
airline_tix

{'first': 100, 'business': nan, 'economy-plus': 50, 'ecomony': 30}

In [ ]:
ser = pd.Series(airline_tix)

In [ ]:
ser

first           100.0
business          NaN
economy-plus     50.0
ecomony          30.0
dtype: float64

In [ ]:
# Interprite the NaN value (liner interpretation).
# Here the assumption  is that the data is in the proper order

In [ ]:
ser.interpolate()

first           100.0
business         75.0
economy-plus     50.0
ecomony          30.0
dtype: float64

In [ ]:
df

  first_name last_name   age  sex  pre_movie_score  post_movie_score
0        Tom     Hanks  63.0    m              7.0              10.0
1        NaN       NaN   NaN  NaN              7.0               NaN
2       Hugh   Jackman  51.0    m              7.0               NaN
3      Oprah   Winfrey  66.0    f              7.0               8.0
4       Emma     Stone  31.0    f              7.0               9.0

## GroupBy

In [ ]:
import pandas as pd
import numpy as np

In [ ]:
df = pd.read_csv('https://raw.githubusercontent.com/cypherkrish/PythonDataScience/main/Data/mpg.csv')

In [ ]:
df

,mpg,cylinders,displacement,horsepower,weight,acceleration,model_year,origin,name
0,18.0,8,307.0,130,3504,12.0,70,1,chevrolet chevelle malibu
1,15.0,8,350.0,165,3693,11.5,70,1,buick skylark 320
2,18.0,8,318.0,150,3436,11.0,70,1,plymouth satellite
3,16.0,8,304.0,150,3433,12.0,70,1,amc rebel sst
4,17.0,8,302.0,140,3449,10.5,70,1,ford torino
...,...,...,...,...,...,...,...,...,...
393,27.0,4,140.0,86,2790,15.6,82,1,ford mustang gl
394,44.0,4,97.0,52,2130,24.6,82,2,vw pickup
395,32.0,4,135.0,84,2295,11.6,82,1,dodge rampage
396,28.0,4,120.0,79,2625,18.6,82,1,ford ranger
397,31.0,4,119.0,82,2720,19.4,82,1,chevy s-10

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 398 entries, 0 to 397
Data columns (total 9 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   mpg           398 non-null    float64
 1   cylinders     398 non-null    int64
 2   displacement  398 non-null    float64
 3   horsepower    398 non-null    object
 4   weight        398 non-null    int64
 5   acceleration  398 non-null    float64
 6   model_year    398 non-null    int64
 7   origin        398 non-null    int64
 8   name          398 non-null    object
dtypes: float64(3), int64(4), object(2)
memory usage: 28.1+ KB

In [ ]:
df['model_year']

0      70
1      70
2      70
3      70
4      70
       ..
393    82
394    82
395    82
396    82
397    82
Name: model_year, Length: 398, dtype: int64

In [ ]:
df['model_year'].unique()

array([70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82])

In [ ]:
df['model_year'].value_counts()

73    40
78    36
76    34
82    31
75    30
70    29
79    29
80    29
81    29
71    28
72    28
77    28
74    27
Name: model_year, dtype: int64

In [ ]:
df.groupby('model_year')

In [ ]:
df.groupby('model_year').mean()

<ipython-input-10-60960c1ac25f>:1: FutureWarning: The default value of numeric_only in DataFrameGroupBy.mean is deprecated. In a future version, numeric_only will default to False. Either specify numeric_only or select only columns which should be valid for the function.
  df.groupby('model_year').mean()

,mpg,cylinders,displacement,weight,acceleration,origin
model_year,,,,,,
70,17.689655,6.758621,281.413793,3372.793103,12.948276,1.310345
71,21.250000,5.571429,209.750000,2995.428571,15.142857,1.428571
72,18.714286,5.821429,218.375000,3237.714286,15.125000,1.535714
73,17.100000,6.375000,256.875000,3419.025000,14.312500,1.375000
74,22.703704,5.259259,171.740741,2877.925926,16.203704,1.666667
75,20.266667,5.600000,205.533333,3176.800000,16.050000,1.466667
76,21.573529,5.647059,197.794118,3078.735294,15.941176,1.470588
77,23.375000,5.464286,191.392857,2997.357143,15.435714,1.571429
78,24.061111,5.361111,177.805556,2861.805556,15.805556,1.611111
79,25.093103,5.827586,206.689655,3055.344828,15.813793,1.275862
80,33.696552,4.137931,115.827586,2436.655172,16.934483,2.206897
81,30.334483,4.620690,135.310345,2522.931034,16.306897,1.965517
82,31.709677,4.193548,128.870968,2453.548387,16.638710,1.645161

In [ ]:
df.groupby('model_year').mean()['mpg']

<ipython-input-11-eed303162ba5>:1: FutureWarning: The default value of numeric_only in DataFrameGroupBy.mean is deprecated. In a future version, numeric_only will default to False. Either specify numeric_only or select only columns which should be valid for the function.
  df.groupby('model_year').mean()['mpg']

model_year
70    17.689655
71    21.250000
72    18.714286
73    17.100000
74    22.703704
75    20.266667
76    21.573529
77    23.375000
78    24.061111
79    25.093103
80    33.696552
81    30.334483
82    31.709677
Name: mpg, dtype: float64

In [ ]:
## GroupBy multiple columns

In [ ]:
df.groupby(['model_year', 'cylinders']).mean()

<ipython-input-13-1d313837d679>:1: FutureWarning: The default value of numeric_only in DataFrameGroupBy.mean is deprecated. In a future version, numeric_only will default to False. Either specify numeric_only or select only columns which should be valid for the function.
  df.groupby(['model_year', 'cylinders']).mean()

                            mpg  displacement       weight  acceleration  \
model_year cylinders
70         4          25.285714    107.000000  2292.571429     16.000000
           6          20.500000    199.000000  2710.500000     15.500000
           8          14.111111    367.555556  3940.055556     11.194444
71         4          27.461538    101.846154  2056.384615     16.961538
           6          18.000000    243.375000  3171.875000     14.750000
           8          13.428571    371.714286  4537.714286     12.214286
72         3          19.000000     70.000000  2330.000000     13.500000
           4          23.428571    111.535714  2382.642857     17.214286
           8          13.615385    344.846154  4228.384615     13.000000
73         3          18.000000     70.000000  2124.000000     13.500000
           4          22.727273    109.272727  2338.090909     17.136364
           6          19.000000    212.250000  2917.125000     15.687500
           8          13.200000    365.250000  4279.050000     12.250000
74         4          27.800000     96.533333  2151.466667     16.400000
           6          17.857143    230.428571  3320.000000     16.857143
           8          14.200000    315.200000  4438.400000     14.700000
75         4          25.250000    114.833333  2489.250000     15.833333
           6          17.583333    233.750000  3398.333333     17.708333
           8          15.666667    330.500000  4108.833333     13.166667
76         4          26.766667    106.333333  2306.600000     16.866667
           6          20.000000    221.400000  3349.600000     17.000000
           8          14.666667    324.000000  4064.666667     13.222222
77         3          21.500000     80.000000  2720.000000     13.500000
           4          29.107143    106.500000  2205.071429     16.064286
           6          19.500000    220.400000  3383.000000     16.900000
           8          16.000000    335.750000  4177.500000     13.662500
78         4          29.576471    112.117647  2296.764706     16.282353
           5          20.300000    131.000000  2830.000000     15.900000
           6          19.066667    213.250000  3314.166667     16.391667
           8          19.050000    300.833333  3563.333333     13.266667
79         4          31.525000    113.583333  2357.583333     15.991667
           5          25.400000    183.000000  3530.000000     20.100000
           6          22.950000    205.666667  3025.833333     15.433333
           8          18.630000    321.400000  3862.900000     15.400000
80         3          23.700000     70.000000  2420.000000     12.500000
           4          34.612000    111.000000  2360.080000     17.144000
           5          36.400000    121.000000  2950.000000     19.900000
           6          25.900000    196.500000  3145.500000     15.050000
81         4          32.814286    108.857143  2275.476190     16.466667
           6          23.428571    184.000000  3093.571429     15.442857
           8          26.600000    350.000000  3725.000000     19.000000
82         4          32.071429    118.571429  2402.321429     16.703571
           6          28.333333    225.000000  2931.666667     16.033333

                        origin
model_year cylinders
70         4          2.285714
           6          1.000000
           8          1.000000
71         4          1.923077
           6          1.000000
           8          1.000000
72         3          3.000000
           4          1.928571
           8          1.000000
73         3          3.000000
           4          2.000000
           6          1.250000
           8          1.000000
74         4          2.200000
           6          1.000000
           8          1.000000
75         4          2.166667
           6          1.000000
           8          1.000000
76         4          1.866667
           6          1.300000
           8          1.000000
77         3          3.000000
           4          1.857143
           6          1.400000
           8          1.000000
78         4          2.117647
           5          2.000000
           6          1.166667
           8          1.000000
79         4          1.583333
           5          2.000000
           6          1.000000
           8          1.000000
80         3          3.000000
           4          2.200000
           5          2.000000
           6          2.000000
81         4          2.095238
           6          1.714286
           8          1.000000
82         4          1.714286
           6          1.000000

In [ ]:
df.groupby(['model_year', 'cylinders']).mean().index

<ipython-input-14-88839300cce2>:1: FutureWarning: The default value of numeric_only in DataFrameGroupBy.mean is deprecated. In a future version, numeric_only will default to False. Either specify numeric_only or select only columns which should be valid for the function.
  df.groupby(['model_year', 'cylinders']).mean().index

MultiIndex([(70, 4),
            (70, 6),
            (70, 8),
            (71, 4),
            (71, 6),
            (71, 8),
            (72, 3),
            (72, 4),
            (72, 8),
            (73, 3),
            (73, 4),
            (73, 6),
            (73, 8),
            (74, 4),
            (74, 6),
            (74, 8),
            (75, 4),
            (75, 6),
            (75, 8),
            (76, 4),
            (76, 6),
            (76, 8),
            (77, 3),
            (77, 4),
            (77, 6),
            (77, 8),
            (78, 4),
            (78, 5),
            (78, 6),
            (78, 8),
            (79, 4),
            (79, 5),
            (79, 6),
            (79, 8),
            (80, 3),
            (80, 4),
            (80, 5),
            (80, 6),
            (81, 4),
            (81, 6),
            (81, 8),
            (82, 4),
            (82, 6)],
           names=['model_year', 'cylinders'])

In [ ]:
df.groupby(['model_year', 'cylinders']).mean()['mpg']

<ipython-input-15-cc18cfcc04f8>:1: FutureWarning: The default value of numeric_only in DataFrameGroupBy.mean is deprecated. In a future version, numeric_only will default to False. Either specify numeric_only or select only columns which should be valid for the function.
  df.groupby(['model_year', 'cylinders']).mean()['mpg']

model_year  cylinders
70          4            25.285714
            6            20.500000
            8            14.111111
71          4            27.461538
            6            18.000000
            8            13.428571
72          3            19.000000
            4            23.428571
            8            13.615385
73          3            18.000000
            4            22.727273
            6            19.000000
            8            13.200000
74          4            27.800000
            6            17.857143
            8            14.200000
75          4            25.250000
            6            17.583333
            8            15.666667
76          4            26.766667
            6            20.000000
            8            14.666667
77          3            21.500000
            4            29.107143
            6            19.500000
            8            16.000000
78          4            29.576471
            5            20.300000
            6            19.066667
            8            19.050000
79          4            31.525000
            5            25.400000
            6            22.950000
            8            18.630000
80          3            23.700000
            4            34.612000
            5            36.400000
            6            25.900000
81          4            32.814286
            6            23.428571
            8            26.600000
82          4            32.071429
            6            28.333333
Name: mpg, dtype: float64

In [ ]:
df.groupby('model_year').describe()

             mpg                                                          \
           count       mean       std   min     25%    50%     75%   max
model_year
70          29.0  17.689655  5.339231   9.0  14.000  16.00  22.000  27.0
71          28.0  21.250000  6.591942  12.0  15.500  19.00  27.000  35.0
72          28.0  18.714286  5.435529  11.0  13.750  18.50  23.000  28.0
73          40.0  17.100000  4.700245  11.0  13.000  16.00  20.000  29.0
74          27.0  22.703704  6.420010  13.0  16.000  24.00  27.000  32.0
75          30.0  20.266667  4.940566  13.0  16.000  19.50  23.000  33.0
76          34.0  21.573529  5.889297  13.0  16.750  21.00  26.375  33.0
77          28.0  23.375000  6.675862  15.0  17.375  21.75  30.000  36.0
78          36.0  24.061111  6.898044  16.2  19.350  20.70  28.000  43.1
79          29.0  25.093103  6.794217  15.5  19.200  23.90  31.800  37.3
80          29.0  33.696552  7.037983  19.1  29.800  32.70  38.100  46.6
81          29.0  30.334483  5.591465  17.6  26.600  31.60  34.400  39.1
82          31.0  31.709677  5.392548  22.0  27.000  32.00  36.000  44.0

           cylinders            ... acceleration       origin            \
               count      mean  ...          75%   max  count      mean
model_year                      ...
70              29.0  6.758621  ...       15.000  20.5   29.0  1.310345
71              28.0  5.571429  ...       16.125  20.5   28.0  1.428571
72              28.0  5.821429  ...       16.625  23.5   28.0  1.535714
73              40.0  6.375000  ...       16.000  21.0   40.0  1.375000
74              27.0  5.259259  ...       17.000  21.0   27.0  1.666667
75              30.0  5.600000  ...       17.375  21.0   30.0  1.466667
76              34.0  5.647059  ...       17.550  22.2   34.0  1.470588
77              28.0  5.464286  ...       16.925  19.0   28.0  1.571429
78              36.0  5.361111  ...       16.825  21.5   36.0  1.611111
79              29.0  5.827586  ...       17.300  24.8   29.0  1.275862
80              29.0  4.137931  ...       18.700  23.7   29.0  2.206897
81              29.0  4.620690  ...       17.300  20.7   29.0  1.965517
82              31.0  4.193548  ...       18.000  24.6   31.0  1.645161


                 std  min  25%  50%  75%  max
model_year
70          0.603765  1.0  1.0  1.0  1.0  3.0
71          0.741798  1.0  1.0  1.0  2.0  3.0
72          0.792658  1.0  1.0  1.0  2.0  3.0
73          0.667467  1.0  1.0  1.0  2.0  3.0
74          0.832050  1.0  1.0  1.0  2.0  3.0
75          0.730297  1.0  1.0  1.0  2.0  3.0
76          0.706476  1.0  1.0  1.0  2.0  3.0
77          0.835711  1.0  1.0  1.0  2.0  3.0
78          0.837608  1.0  1.0  1.0  2.0  3.0
79          0.591400  1.0  1.0  1.0  1.0  3.0
80          0.818505  1.0  2.0  2.0  3.0  3.0
81          0.944259  1.0  1.0  2.0  3.0  3.0
82          0.914636  1.0  1.0  1.0  3.0  3.0

[13 rows x 48 columns]

In [ ]:
df.groupby('model_year').describe().transpose()

model_year                   70           71           72           73  \
mpg          count    29.000000    28.000000    28.000000    40.000000
             mean     17.689655    21.250000    18.714286    17.100000
             std       5.339231     6.591942     5.435529     4.700245
             min       9.000000    12.000000    11.000000    11.000000
             25%      14.000000    15.500000    13.750000    13.000000
             50%      16.000000    19.000000    18.500000    16.000000
             75%      22.000000    27.000000    23.000000    20.000000
             max      27.000000    35.000000    28.000000    29.000000
cylinders    count    29.000000    28.000000    28.000000    40.000000
             mean      6.758621     5.571429     5.821429     6.375000
             std       1.724926     1.665079     2.073708     1.807215
             min       4.000000     4.000000     3.000000     3.000000
             25%       6.000000     4.000000     4.000000     4.000000
             50%       8.000000     6.000000     4.000000     7.000000
             75%       8.000000     6.500000     8.000000     8.000000
             max       8.000000     8.000000     8.000000     8.000000
displacement count    29.000000    28.000000    28.000000    40.000000
             mean    281.413793   209.750000   218.375000   256.875000
             std     124.421380   115.102410   123.781964   121.722085
             min      97.000000    71.000000    70.000000    68.000000
             25%     198.000000    97.750000   109.250000   121.750000
             50%     307.000000   228.500000   131.000000   276.000000
             75%     383.000000   273.000000   326.000000   350.250000
             max     455.000000   400.000000   429.000000   455.000000
weight       count    29.000000    28.000000    28.000000    40.000000
             mean   3372.793103  2995.428571  3237.714286  3419.025000
             std     852.868663  1061.830859   974.520960   974.809133
             min    1835.000000  1613.000000  2100.000000  1867.000000
             25%    2648.000000  2110.750000  2285.500000  2554.500000
             50%    3449.000000  2798.000000  2956.000000  3338.500000
             75%    4312.000000  3603.250000  4169.750000  4247.250000
             max    4732.000000  5140.000000  4633.000000  4997.000000
acceleration count    29.000000    28.000000    28.000000    40.000000
             mean     12.948276    15.142857    15.125000    14.312500
             std       3.330982     2.666171     2.850032     2.754222
             min       8.000000    11.500000    11.000000     9.500000
             25%      10.000000    13.375000    13.375000    12.500000
             50%      12.500000    14.500000    14.500000    14.000000
             75%      15.000000    16.125000    16.625000    16.000000
             max      20.500000    20.500000    23.500000    21.000000
origin       count    29.000000    28.000000    28.000000    40.000000
             mean      1.310345     1.428571     1.535714     1.375000
             std       0.603765     0.741798     0.792658     0.667467
             min       1.000000     1.000000     1.000000     1.000000
             25%       1.000000     1.000000     1.000000     1.000000
             50%       1.000000     1.000000     1.000000     1.000000
             75%       1.000000     2.000000     2.000000     2.000000
             max       3.000000     3.000000     3.000000     3.000000

model_year                   74           75           76           77  \
mpg          count    27.000000    30.000000    34.000000    28.000000
             mean     22.703704    20.266667    21.573529    23.375000
             std       6.420010     4.940566     5.889297     6.675862
             min      13.000000    13.000000    13.000000    15.000000
             25%      16.000000    16.000000    16.750000    17.375000
             50%      24.000000    19.500000    21.000000    21.750000
             75%      27.000000    23.000000    26.375000    30.000000
             max      32.000000    33.000000    33.000000    36.000000
cylinders    count    27.000000    30.000000    34.000000    28.000000
             mean      5.259259     5.600000     5.647059     5.464286
             std       1.583390     1.522249     1.667558     1.815206
             min       4.000000     4.000000     4.000000     3.000000
             25%       4.000000     4.000000     4.000000     4.000000
             50%       4.000000     6.000000     6.000000     4.000000
             75%       6.000000     6.000000     7.500000     8.000000
             max       8.000000     8.000000     8.000000     8.000000
displacement count    27.000000    30.000000    34.000000    28.000000
             mean    171.740741   205.533333   197.794118   191.392857
             std      92.601127    87.669730    94.422256   107.813742
             min      71.000000    90.000000    85.000000    79.000000
             25%      90.000000   121.000000   102.500000    97.750000
             50%     122.000000   228.000000   184.000000   143.000000
             75%     250.000000   250.000000   291.000000   270.500000
             max     350.000000   400.000000   351.000000   400.000000
weight       count    27.000000    30.000000    34.000000    28.000000
             mean   2877.925926  3176.800000  3078.735294  2997.357143
             std     949.308571   765.179781   821.371481   912.825902
             min    1649.000000  1795.000000  1795.000000  1825.000000
             25%    2116.500000  2676.750000  2228.750000  2135.000000
             50%    2489.000000  3098.500000  3171.500000  2747.500000
             75%    3622.500000  3662.250000  3803.750000  3925.000000
             max    4699.000000  4668.000000  4380.000000  4335.000000
acceleration count    27.000000    30.000000    34.000000    28.000000
             mean     16.203704    16.050000    15.941176    15.435714
             std       1.688532     2.471737     2.801419     2.273391
             min      13.500000    11.500000    12.000000    11.100000
             25%      15.250000    14.125000    13.925000    14.000000
             50%      16.000000    16.000000    15.500000    15.650000
             75%      17.000000    17.375000    17.550000    16.925000
             max      21.000000    21.000000    22.200000    19.000000
origin       count    27.000000    30.000000    34.000000    28.000000
             mean      1.666667     1.466667     1.470588     1.571429
             std       0.832050     0.730297     0.706476     0.835711
             min       1.000000     1.000000     1.000000     1.000000
             25%       1.000000     1.000000     1.000000     1.000000
             50%       1.000000     1.000000     1.000000     1.000000
             75%       2.000000     2.000000     2.000000     2.000000
             max       3.000000     3.000000     3.000000     3.000000

model_year                   78           79           80           81  \
mpg          count    36.000000    29.000000    29.000000    29.000000
             mean     24.061111    25.093103    33.696552    30.334483
             std       6.898044     6.794217     7.037983     5.591465
             min      16.200000    15.500000    19.100000    17.600000
             25%      19.350000    19.200000    29.800000    26.600000
             50%      20.700000    23.900000    32.700000    31.600000
             75%      28.000000    31.800000    38.100000    34.400000
             max      43.100000    37.300000    46.600000    39.100000
cylinders    count    36.000000    29.000000    29.000000    29.000000
             mean      5.361111     5.827586     4.137931     4.620690
             std       1.495761     1.774199     0.580895     1.082781
             min       4.000000     4.000000     3.000000     4.000000
             25%       4.000000     4.000000     4.000000     4.000000
             50%       5.500000     6.000000     4.000000     4.000000
             75%       6.000000     8.000000     4.000000     6.000000
             max       8.000000     8.000000     6.000000     8.000000
displacement count    36.000000    29.000000    29.000000    29.000000
             mean    177.805556   206.689655   115.827586   135.310345
             std      76.012713    96.307581    33.744914    58.387929
             min      78.000000    85.000000    70.000000    79.000000
             25%     115.500000   121.000000    90.000000    98.000000
             50%     159.500000   183.000000   107.000000   119.000000
             75%     231.000000   302.000000   140.000000   151.000000
             max     318.000000   360.000000   225.000000   350.000000
weight       count    36.000000    29.000000    29.000000    29.000000
             mean   2861.805556  3055.344828  2436.655172  2522.931034
             std     626.023907   747.881497   432.235491   533.600501
             min    1800.000000  1915.000000  1835.000000  1755.000000
             25%    2282.500000  2556.000000  2110.000000  2065.000000
             50%    2910.000000  3190.000000  2335.000000  2385.000000
             75%    3410.000000  3725.000000  2800.000000  2900.000000
             max    4080.000000  4360.000000  3381.000000  3725.000000
acceleration count    36.000000    29.000000    29.000000    29.000000
             mean     15.805556    15.813793    16.934483    16.306897
             std       2.129915     2.952931     2.826694     2.192509
             min      11.200000    11.300000    11.400000    12.600000
             25%      14.475000    14.000000    15.100000    14.800000
             50%      15.750000    15.000000    16.500000    16.200000
             75%      16.825000    17.300000    18.700000    17.300000
             max      21.500000    24.800000    23.700000    20.700000
origin       count    36.000000    29.000000    29.000000    29.000000
             mean      1.611111     1.275862     2.206897     1.965517
             std       0.837608     0.591400     0.818505     0.944259
             min       1.000000     1.000000     1.000000     1.000000
             25%       1.000000     1.000000     2.000000     1.000000
             50%       1.000000     1.000000     2.000000     2.000000
             75%       2.000000     1.000000     3.000000     3.000000
             max       3.000000     3.000000     3.000000     3.000000

model_year                   82
mpg          count    31.000000
             mean     31.709677
             std       5.392548
             min      22.000000
             25%      27.000000
             50%      32.000000
             75%      36.000000
             max      44.000000
cylinders    count    31.000000
             mean      4.193548
             std       0.601074
             min       4.000000
             25%       4.000000
             50%       4.000000
             75%       4.000000
             max       6.000000
displacement count    31.000000
             mean    128.870968
             std      39.352037
             min      91.000000
             25%     105.000000
             50%     119.000000
             75%     142.000000
             max     262.000000
weight       count    31.000000
             mean   2453.548387
             std     354.276713
             min    1965.000000
             25%    2127.500000
             50%    2525.000000
             75%    2727.500000
             max    3035.000000
acceleration count    31.000000
             mean     16.638710
             std       2.484844
             min      11.600000
             25%      14.850000
             50%      16.400000
             75%      18.000000
             max      24.600000
origin       count    31.000000
             mean      1.645161
             std       0.914636
             min       1.000000
             25%       1.000000
             50%       1.000000
             75%       3.000000
             max       3.000000

In [ ]:
year_cy1 = df.groupby(['model_year', 'cylinders']).mean()

<ipython-input-18-de41e7f9e8e7>:1: FutureWarning: The default value of numeric_only in DataFrameGroupBy.mean is deprecated. In a future version, numeric_only will default to False. Either specify numeric_only or select only columns which should be valid for the function.
  year_cy1 = df.groupby(['model_year', 'cylinders']).mean()

In [ ]:
year_cy1

                            mpg  displacement       weight  acceleration  \
model_year cylinders
70         4          25.285714    107.000000  2292.571429     16.000000
           6          20.500000    199.000000  2710.500000     15.500000
           8          14.111111    367.555556  3940.055556     11.194444
71         4          27.461538    101.846154  2056.384615     16.961538
           6          18.000000    243.375000  3171.875000     14.750000
           8          13.428571    371.714286  4537.714286     12.214286
72         3          19.000000     70.000000  2330.000000     13.500000
           4          23.428571    111.535714  2382.642857     17.214286
           8          13.615385    344.846154  4228.384615     13.000000
73         3          18.000000     70.000000  2124.000000     13.500000
           4          22.727273    109.272727  2338.090909     17.136364
           6          19.000000    212.250000  2917.125000     15.687500
           8          13.200000    365.250000  4279.050000     12.250000
74         4          27.800000     96.533333  2151.466667     16.400000
           6          17.857143    230.428571  3320.000000     16.857143
           8          14.200000    315.200000  4438.400000     14.700000
75         4          25.250000    114.833333  2489.250000     15.833333
           6          17.583333    233.750000  3398.333333     17.708333
           8          15.666667    330.500000  4108.833333     13.166667
76         4          26.766667    106.333333  2306.600000     16.866667
           6          20.000000    221.400000  3349.600000     17.000000
           8          14.666667    324.000000  4064.666667     13.222222
77         3          21.500000     80.000000  2720.000000     13.500000
           4          29.107143    106.500000  2205.071429     16.064286
           6          19.500000    220.400000  3383.000000     16.900000
           8          16.000000    335.750000  4177.500000     13.662500
78         4          29.576471    112.117647  2296.764706     16.282353
           5          20.300000    131.000000  2830.000000     15.900000
           6          19.066667    213.250000  3314.166667     16.391667
           8          19.050000    300.833333  3563.333333     13.266667
79         4          31.525000    113.583333  2357.583333     15.991667
           5          25.400000    183.000000  3530.000000     20.100000
           6          22.950000    205.666667  3025.833333     15.433333
           8          18.630000    321.400000  3862.900000     15.400000
80         3          23.700000     70.000000  2420.000000     12.500000
           4          34.612000    111.000000  2360.080000     17.144000
           5          36.400000    121.000000  2950.000000     19.900000
           6          25.900000    196.500000  3145.500000     15.050000
81         4          32.814286    108.857143  2275.476190     16.466667
           6          23.428571    184.000000  3093.571429     15.442857
           8          26.600000    350.000000  3725.000000     19.000000
82         4          32.071429    118.571429  2402.321429     16.703571
           6          28.333333    225.000000  2931.666667     16.033333

                        origin
model_year cylinders
70         4          2.285714
           6          1.000000
           8          1.000000
71         4          1.923077
           6          1.000000
           8          1.000000
72         3          3.000000
           4          1.928571
           8          1.000000
73         3          3.000000
           4          2.000000
           6          1.250000
           8          1.000000
74         4          2.200000
           6          1.000000
           8          1.000000
75         4          2.166667
           6          1.000000
           8          1.000000
76         4          1.866667
           6          1.300000
           8          1.000000
77         3          3.000000
           4          1.857143
           6          1.400000
           8          1.000000
78         4          2.117647
           5          2.000000
           6          1.166667
           8          1.000000
79         4          1.583333
           5          2.000000
           6          1.000000
           8          1.000000
80         3          3.000000
           4          2.200000
           5          2.000000
           6          2.000000
81         4          2.095238
           6          1.714286
           8          1.000000
82         4          1.714286
           6          1.000000

In [ ]:
year_cy1.index.names

FrozenList(['model_year', 'cylinders'])

In [ ]:
year_cy1.index.levels

FrozenList([[70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82], [3, 4, 5, 6, 8]])

In [ ]:
year_cy1.loc[70]

                 mpg  displacement       weight  acceleration    origin
cylinders
4          25.285714    107.000000  2292.571429     16.000000  2.285714
6          20.500000    199.000000  2710.500000     15.500000  1.000000
8          14.111111    367.555556  3940.055556     11.194444  1.000000

In [ ]:
year_cy1.loc[[70, 82]]

                            mpg  displacement       weight  acceleration  \
model_year cylinders
70         4          25.285714    107.000000  2292.571429     16.000000
           6          20.500000    199.000000  2710.500000     15.500000
           8          14.111111    367.555556  3940.055556     11.194444
82         4          32.071429    118.571429  2402.321429     16.703571
           6          28.333333    225.000000  2931.666667     16.033333

                        origin
model_year cylinders
70         4          2.285714
           6          1.000000
           8          1.000000
82         4          1.714286
           6          1.000000

In [ ]:
year_cy1.index

MultiIndex([(70, 4),
            (70, 6),
            (70, 8),
            (71, 4),
            (71, 6),
            (71, 8),
            (72, 3),
            (72, 4),
            (72, 8),
            (73, 3),
            (73, 4),
            (73, 6),
            (73, 8),
            (74, 4),
            (74, 6),
            (74, 8),
            (75, 4),
            (75, 6),
            (75, 8),
            (76, 4),
            (76, 6),
            (76, 8),
            (77, 3),
            (77, 4),
            (77, 6),
            (77, 8),
            (78, 4),
            (78, 5),
            (78, 6),
            (78, 8),
            (79, 4),
            (79, 5),
            (79, 6),
            (79, 8),
            (80, 3),
            (80, 4),
            (80, 5),
            (80, 6),
            (81, 4),
            (81, 6),
            (81, 8),
            (82, 4),
            (82, 6)],
           names=['model_year', 'cylinders'])

In [ ]:
year_cy1.loc[(70, 4)]

mpg               25.285714
displacement     107.000000
weight          2292.571429
acceleration      16.000000
origin             2.285714
Name: (70, 4), dtype: float64

In [ ]:
year_cy1.xs(key=70, level = 'model_year')

                 mpg  displacement       weight  acceleration    origin
cylinders
4          25.285714    107.000000  2292.571429     16.000000  2.285714
6          20.500000    199.000000  2710.500000     15.500000  1.000000
8          14.111111    367.555556  3940.055556     11.194444  1.000000

In [ ]:
year_cy1.loc[[70,80]]

                            mpg  displacement       weight  acceleration  \
model_year cylinders
70         4          25.285714    107.000000  2292.571429     16.000000
           6          20.500000    199.000000  2710.500000     15.500000
           8          14.111111    367.555556  3940.055556     11.194444
80         3          23.700000     70.000000  2420.000000     12.500000
           4          34.612000    111.000000  2360.080000     17.144000
           5          36.400000    121.000000  2950.000000     19.900000
           6          25.900000    196.500000  3145.500000     15.050000

                        origin
model_year cylinders
70         4          2.285714
           6          1.000000
           8          1.000000
80         3          3.000000
           4          2.200000
           5          2.000000
           6          2.000000

In [ ]:
year_cy1.xs(key=4,level = 'cylinders')

                  mpg  displacement       weight  acceleration    origin
model_year
70          25.285714    107.000000  2292.571429     16.000000  2.285714
71          27.461538    101.846154  2056.384615     16.961538  1.923077
72          23.428571    111.535714  2382.642857     17.214286  1.928571
73          22.727273    109.272727  2338.090909     17.136364  2.000000
74          27.800000     96.533333  2151.466667     16.400000  2.200000
75          25.250000    114.833333  2489.250000     15.833333  2.166667
76          26.766667    106.333333  2306.600000     16.866667  1.866667
77          29.107143    106.500000  2205.071429     16.064286  1.857143
78          29.576471    112.117647  2296.764706     16.282353  2.117647
79          31.525000    113.583333  2357.583333     15.991667  1.583333
80          34.612000    111.000000  2360.080000     17.144000  2.200000
81          32.814286    108.857143  2275.476190     16.466667  2.095238
82          32.071429    118.571429  2402.321429     16.703571  1.714286

In [ ]:
four_cyl = year_cy1.xs(key=4,level = 'cylinders')

In [ ]:
four_cyl

                  mpg  displacement       weight  acceleration    origin
model_year
70          25.285714    107.000000  2292.571429     16.000000  2.285714
71          27.461538    101.846154  2056.384615     16.961538  1.923077
72          23.428571    111.535714  2382.642857     17.214286  1.928571
73          22.727273    109.272727  2338.090909     17.136364  2.000000
74          27.800000     96.533333  2151.466667     16.400000  2.200000
75          25.250000    114.833333  2489.250000     15.833333  2.166667
76          26.766667    106.333333  2306.600000     16.866667  1.866667
77          29.107143    106.500000  2205.071429     16.064286  1.857143
78          29.576471    112.117647  2296.764706     16.282353  2.117647
79          31.525000    113.583333  2357.583333     15.991667  1.583333
80          34.612000    111.000000  2360.080000     17.144000  2.200000
81          32.814286    108.857143  2275.476190     16.466667  2.095238
82          32.071429    118.571429  2402.321429     16.703571  1.714286

In [ ]:
df[df['cylinders'].isin([6, 8])].groupby(['model_year', 'cylinders']).mean()

<ipython-input-35-1ea7b065181a>:1: FutureWarning: The default value of numeric_only in DataFrameGroupBy.mean is deprecated. In a future version, numeric_only will default to False. Either specify numeric_only or select only columns which should be valid for the function.
  df[df['cylinders'].isin([6, 8])].groupby(['model_year', 'cylinders']).mean()

                            mpg  displacement       weight  acceleration  \
model_year cylinders
70         6          20.500000    199.000000  2710.500000     15.500000
           8          14.111111    367.555556  3940.055556     11.194444
71         6          18.000000    243.375000  3171.875000     14.750000
           8          13.428571    371.714286  4537.714286     12.214286
72         8          13.615385    344.846154  4228.384615     13.000000
73         6          19.000000    212.250000  2917.125000     15.687500
           8          13.200000    365.250000  4279.050000     12.250000
74         6          17.857143    230.428571  3320.000000     16.857143
           8          14.200000    315.200000  4438.400000     14.700000
75         6          17.583333    233.750000  3398.333333     17.708333
           8          15.666667    330.500000  4108.833333     13.166667
76         6          20.000000    221.400000  3349.600000     17.000000
           8          14.666667    324.000000  4064.666667     13.222222
77         6          19.500000    220.400000  3383.000000     16.900000
           8          16.000000    335.750000  4177.500000     13.662500
78         6          19.066667    213.250000  3314.166667     16.391667
           8          19.050000    300.833333  3563.333333     13.266667
79         6          22.950000    205.666667  3025.833333     15.433333
           8          18.630000    321.400000  3862.900000     15.400000
80         6          25.900000    196.500000  3145.500000     15.050000
81         6          23.428571    184.000000  3093.571429     15.442857
           8          26.600000    350.000000  3725.000000     19.000000
82         6          28.333333    225.000000  2931.666667     16.033333

                        origin
model_year cylinders
70         6          1.000000
           8          1.000000
71         6          1.000000
           8          1.000000
72         8          1.000000
73         6          1.250000
           8          1.000000
74         6          1.000000
           8          1.000000
75         6          1.000000
           8          1.000000
76         6          1.300000
           8          1.000000
77         6          1.400000
           8          1.000000
78         6          1.166667
           8          1.000000
79         6          1.000000
           8          1.000000
80         6          2.000000
81         6          1.714286
           8          1.000000
82         6          1.000000

In [ ]:
year_cy1

                            mpg  displacement       weight  acceleration  \
model_year cylinders
70         4          25.285714    107.000000  2292.571429     16.000000
           6          20.500000    199.000000  2710.500000     15.500000
           8          14.111111    367.555556  3940.055556     11.194444
71         4          27.461538    101.846154  2056.384615     16.961538
           6          18.000000    243.375000  3171.875000     14.750000
           8          13.428571    371.714286  4537.714286     12.214286
72         3          19.000000     70.000000  2330.000000     13.500000
           4          23.428571    111.535714  2382.642857     17.214286
           8          13.615385    344.846154  4228.384615     13.000000
73         3          18.000000     70.000000  2124.000000     13.500000
           4          22.727273    109.272727  2338.090909     17.136364
           6          19.000000    212.250000  2917.125000     15.687500
           8          13.200000    365.250000  4279.050000     12.250000
74         4          27.800000     96.533333  2151.466667     16.400000
           6          17.857143    230.428571  3320.000000     16.857143
           8          14.200000    315.200000  4438.400000     14.700000
75         4          25.250000    114.833333  2489.250000     15.833333
           6          17.583333    233.750000  3398.333333     17.708333
           8          15.666667    330.500000  4108.833333     13.166667
76         4          26.766667    106.333333  2306.600000     16.866667
           6          20.000000    221.400000  3349.600000     17.000000
           8          14.666667    324.000000  4064.666667     13.222222
77         3          21.500000     80.000000  2720.000000     13.500000
           4          29.107143    106.500000  2205.071429     16.064286
           6          19.500000    220.400000  3383.000000     16.900000
           8          16.000000    335.750000  4177.500000     13.662500
78         4          29.576471    112.117647  2296.764706     16.282353
           5          20.300000    131.000000  2830.000000     15.900000
           6          19.066667    213.250000  3314.166667     16.391667
           8          19.050000    300.833333  3563.333333     13.266667
79         4          31.525000    113.583333  2357.583333     15.991667
           5          25.400000    183.000000  3530.000000     20.100000
           6          22.950000    205.666667  3025.833333     15.433333
           8          18.630000    321.400000  3862.900000     15.400000
80         3          23.700000     70.000000  2420.000000     12.500000
           4          34.612000    111.000000  2360.080000     17.144000
           5          36.400000    121.000000  2950.000000     19.900000
           6          25.900000    196.500000  3145.500000     15.050000
81         4          32.814286    108.857143  2275.476190     16.466667
           6          23.428571    184.000000  3093.571429     15.442857
           8          26.600000    350.000000  3725.000000     19.000000
82         4          32.071429    118.571429  2402.321429     16.703571
           6          28.333333    225.000000  2931.666667     16.033333

                        origin
model_year cylinders
70         4          2.285714
           6          1.000000
           8          1.000000
71         4          1.923077
           6          1.000000
           8          1.000000
72         3          3.000000
           4          1.928571
           8          1.000000
73         3          3.000000
           4          2.000000
           6          1.250000
           8          1.000000
74         4          2.200000
           6          1.000000
           8          1.000000
75         4          2.166667
           6          1.000000
           8          1.000000
76         4          1.866667
           6          1.300000
           8          1.000000
77         3          3.000000
           4          1.857143
           6          1.400000
           8          1.000000
78         4          2.117647
           5          2.000000
           6          1.166667
           8          1.000000
79         4          1.583333
           5          2.000000
           6          1.000000
           8          1.000000
80         3          3.000000
           4          2.200000
           5          2.000000
           6          2.000000
81         4          2.095238
           6          1.714286
           8          1.000000
82         4          1.714286
           6          1.000000

In [ ]:
year_cy1.swaplevel()

,,mpg,displacement,weight,acceleration,origin
cylinders,model_year,,,,,
4,70,25.285714,107.000000,2292.571429,16.000000,2.285714
6,70,20.500000,199.000000,2710.500000,15.500000,1.000000
8,70,14.111111,367.555556,3940.055556,11.194444,1.000000
4,71,27.461538,101.846154,2056.384615,16.961538,1.923077
6,71,18.000000,243.375000,3171.875000,14.750000,1.000000
8,71,13.428571,371.714286,4537.714286,12.214286,1.000000
3,72,19.000000,70.000000,2330.000000,13.500000,3.000000
4,72,23.428571,111.535714,2382.642857,17.214286,1.928571
8,72,13.615385,344.846154,4228.384615,13.000000,1.000000
3,73,18.000000,70.000000,2124.000000,13.500000,3.000000
4,73,22.727273,109.272727,2338.090909,17.136364,2.000000
6,73,19.000000,212.250000,2917.125000,15.687500,1.250000
8,73,13.200000,365.250000,4279.050000,12.250000,1.000000
4,74,27.800000,96.533333,2151.466667,16.400000,2.200000
6,74,17.857143,230.428571,3320.000000,16.857143,1.000000
8,74,14.200000,315.200000,4438.400000,14.700000,1.000000
4,75,25.250000,114.833333,2489.250000,15.833333,2.166667
6,75,17.583333,233.750000,3398.333333,17.708333,1.000000
8,75,15.666667,330.500000,4108.833333,13.166667,1.000000
4,76,26.766667,106.333333,2306.600000,16.866667,1.866667
6,76,20.000000,221.400000,3349.600000,17.000000,1.300000
8,76,14.666667,324.000000,4064.666667,13.222222,1.000000
3,77,21.500000,80.000000,2720.000000,13.500000,3.000000
4,77,29.107143,106.500000,2205.071429,16.064286,1.857143
6,77,19.500000,220.400000,3383.000000,16.900000,1.400000
8,77,16.000000,335.750000,4177.500000,13.662500,1.000000
4,78,29.576471,112.117647,2296.764706,16.282353,2.117647
5,78,20.300000,131.000000,2830.000000,15.900000,2.000000
6,78,19.066667,213.250000,3314.166667,16.391667,1.166667
8,78,19.050000,300.833333,3563.333333,13.266667,1.000000
4,79,31.525000,113.583333,2357.583333,15.991667,1.583333
5,79,25.400000,183.000000,3530.000000,20.100000,2.000000
6,79,22.950000,205.666667,3025.833333,15.433333,1.000000
8,79,18.630000,321.400000,3862.900000,15.400000,1.000000
3,80,23.700000,70.000000,2420.000000,12.500000,3.000000
4,80,34.612000,111.000000,2360.080000,17.144000,2.200000
5,80,36.400000,121.000000,2950.000000,19.900000,2.000000
6,80,25.900000,196.500000,3145.500000,15.050000,2.000000
4,81,32.814286,108.857143,2275.476190,16.466667,2.095238
6,81,23.428571,184.000000,3093.571429,15.442857,1.714286
8,81,26.600000,350.000000,3725.000000,19.000000,1.000000
4,82,32.071429,118.571429,2402.321429,16.703571,1.714286
6,82,28.333333,225.000000,2931.666667,16.033333,1.000000

In [ ]:
year_cy1.sort_index(level = 'model_year', ascending = False)

                            mpg  displacement       weight  acceleration  \
model_year cylinders
82         6          28.333333    225.000000  2931.666667     16.033333
           4          32.071429    118.571429  2402.321429     16.703571
81         8          26.600000    350.000000  3725.000000     19.000000
           6          23.428571    184.000000  3093.571429     15.442857
           4          32.814286    108.857143  2275.476190     16.466667
80         6          25.900000    196.500000  3145.500000     15.050000
           5          36.400000    121.000000  2950.000000     19.900000
           4          34.612000    111.000000  2360.080000     17.144000
           3          23.700000     70.000000  2420.000000     12.500000
79         8          18.630000    321.400000  3862.900000     15.400000
           6          22.950000    205.666667  3025.833333     15.433333
           5          25.400000    183.000000  3530.000000     20.100000
           4          31.525000    113.583333  2357.583333     15.991667
78         8          19.050000    300.833333  3563.333333     13.266667
           6          19.066667    213.250000  3314.166667     16.391667
           5          20.300000    131.000000  2830.000000     15.900000
           4          29.576471    112.117647  2296.764706     16.282353
77         8          16.000000    335.750000  4177.500000     13.662500
           6          19.500000    220.400000  3383.000000     16.900000
           4          29.107143    106.500000  2205.071429     16.064286
           3          21.500000     80.000000  2720.000000     13.500000
76         8          14.666667    324.000000  4064.666667     13.222222
           6          20.000000    221.400000  3349.600000     17.000000
           4          26.766667    106.333333  2306.600000     16.866667
75         8          15.666667    330.500000  4108.833333     13.166667
           6          17.583333    233.750000  3398.333333     17.708333
           4          25.250000    114.833333  2489.250000     15.833333
74         8          14.200000    315.200000  4438.400000     14.700000
           6          17.857143    230.428571  3320.000000     16.857143
           4          27.800000     96.533333  2151.466667     16.400000
73         8          13.200000    365.250000  4279.050000     12.250000
           6          19.000000    212.250000  2917.125000     15.687500
           4          22.727273    109.272727  2338.090909     17.136364
           3          18.000000     70.000000  2124.000000     13.500000
72         8          13.615385    344.846154  4228.384615     13.000000
           4          23.428571    111.535714  2382.642857     17.214286
           3          19.000000     70.000000  2330.000000     13.500000
71         8          13.428571    371.714286  4537.714286     12.214286
           6          18.000000    243.375000  3171.875000     14.750000
           4          27.461538    101.846154  2056.384615     16.961538
70         8          14.111111    367.555556  3940.055556     11.194444
           6          20.500000    199.000000  2710.500000     15.500000
           4          25.285714    107.000000  2292.571429     16.000000

                        origin
model_year cylinders
82         6          1.000000
           4          1.714286
81         8          1.000000
           6          1.714286
           4          2.095238
80         6          2.000000
           5          2.000000
           4          2.200000
           3          3.000000
79         8          1.000000
           6          1.000000
           5          2.000000
           4          1.583333
78         8          1.000000
           6          1.166667
           5          2.000000
           4          2.117647
77         8          1.000000
           6          1.400000
           4          1.857143
           3          3.000000
76         8          1.000000
           6          1.300000
           4          1.866667
75         8          1.000000
           6          1.000000
           4          2.166667
74         8          1.000000
           6          1.000000
           4          2.200000
73         8          1.000000
           6          1.250000
           4          2.000000
           3          3.000000
72         8          1.000000
           4          1.928571
           3          3.000000
71         8          1.000000
           6          1.000000
           4          1.923077
70         8          1.000000
           6          1.000000
           4          2.285714

In [ ]:
 # Aggregate functions

In [ ]:
df

,mpg,cylinders,displacement,horsepower,weight,acceleration,model_year,origin,name
0,18.0,8,307.0,130,3504,12.0,70,1,chevrolet chevelle malibu
1,15.0,8,350.0,165,3693,11.5,70,1,buick skylark 320
2,18.0,8,318.0,150,3436,11.0,70,1,plymouth satellite
3,16.0,8,304.0,150,3433,12.0,70,1,amc rebel sst
4,17.0,8,302.0,140,3449,10.5,70,1,ford torino
...,...,...,...,...,...,...,...,...,...
393,27.0,4,140.0,86,2790,15.6,82,1,ford mustang gl
394,44.0,4,97.0,52,2130,24.6,82,2,vw pickup
395,32.0,4,135.0,84,2295,11.6,82,1,dodge rampage
396,28.0,4,120.0,79,2625,18.6,82,1,ford ranger
397,31.0,4,119.0,82,2720,19.4,82,1,chevy s-10

In [ ]:
df.agg(['std', 'mean'])

<ipython-input-43-f4f9fe05dba8>:1: FutureWarning: ['horsepower', 'name'] did not aggregate successfully. If any error is raised this will raise in a future version of pandas. Drop these columns/ops to avoid this warning.
  df.agg(['std', 'mean'])

,mpg,cylinders,displacement,weight,acceleration,model_year,origin
std,7.815984,1.701004,104.269838,846.841774,2.757689,3.697627,0.802055
mean,23.514573,5.454774,193.425879,2970.424623,15.568090,76.010050,1.572864

In [ ]:
df.agg(['std', 'mean'])['mpg']

<ipython-input-44-2814c6a5a853>:1: FutureWarning: ['horsepower', 'name'] did not aggregate successfully. If any error is raised this will raise in a future version of pandas. Drop these columns/ops to avoid this warning.
  df.agg(['std', 'mean'])['mpg']

std      7.815984
mean    23.514573
Name: mpg, dtype: float64

In [ ]:
df.agg({'mpg':['max', 'mean'], 'weight': ['mean', 'std']})  # Most  advanced function

            mpg       weight
max   46.600000          NaN
mean  23.514573  2970.424623
std         NaN   846.841774

## Data Frames - Concatenation

In [ ]:
import numpy as np
import pandas as pd

In [ ]:
data_one = {'A': ['A0', 'A1', 'A2', 'A3'], 'B': ['B0', 'B1', 'B2', 'B3']}

In [ ]:
data_two =  {'C': ['C0', 'C1', 'C2', 'C3'], 'D': ['D0', 'D1', 'D2', 'D3']}

In [ ]:
one = pd.DataFrame(data_one)

In [ ]:
two = pd.DataFrame(data_two)

In [ ]:
data_one

{'A': ['A0', 'A1', 'A2', 'A3'], 'B': ['B0', 'B1', 'B2', 'B3']}

In [ ]:
one

    A   B
0  A0  B0
1  A1  B1
2  A2  B2
3  A3  B3

In [ ]:
data_two

{'C': ['C0', 'C1', 'C2', 'C3'], 'D': ['D0', 'D1', 'D2', 'D3']}

In [ ]:
two

    C   D
0  C0  D0
1  C1  D1
2  C2  D2
3  C3  D3

In [ ]:
pd.concat([one, two]) # Default join DFs is by rows

     A    B    C    D
0   A0   B0  NaN  NaN
1   A1   B1  NaN  NaN
2   A2   B2  NaN  NaN
3   A3   B3  NaN  NaN
0  NaN  NaN   C0   D0
1  NaN  NaN   C1   D1
2  NaN  NaN   C2   D2
3  NaN  NaN   C3   D3

In [ ]:
pd.concat([one, two], axis=0)  # This is the default. Joining by rows

     A    B    C    D
0   A0   B0  NaN  NaN
1   A1   B1  NaN  NaN
2   A2   B2  NaN  NaN
3   A3   B3  NaN  NaN
0  NaN  NaN   C0   D0
1  NaN  NaN   C1   D1
2  NaN  NaN   C2   D2
3  NaN  NaN   C3   D3

In [ ]:
pd.concat([one, two], axis=1) # Join DFs by columns

    A   B   C   D
0  A0  B0  C0  D0
1  A1  B1  C1  D1
2  A2  B2  C2  D2
3  A3  B3  C3  D3

In [ ]:
pd.concat([two, one], axis=1) # Join Dfs by columns

    C   D   A   B
0  C0  D0  A0  B0
1  C1  D1  A1  B1
2  C2  D2  A2  B2
3  C3  D3  A3  B3

In [ ]:
one

    A   B
0  A0  B0
1  A1  B1
2  A2  B2
3  A3  B3

In [ ]:
two

    C   D
0  C0  D0
1  C1  D1
2  C2  D2
3  C3  D3

In [ ]:
two.columns = one.columns # let us say both DFs have same column names

In [ ]:
pd.concat([one, two], axis=1)

    A   B   A   B
0  A0  B0  C0  D0
1  A1  B1  C1  D1
2  A2  B2  C2  D2
3  A3  B3  C3  D3

In [ ]:
pd.concat([one, two])

    A   B
0  A0  B0
1  A1  B1
2  A2  B2
3  A3  B3
0  C0  D0
1  C1  D1
2  C2  D2
3  C3  D3

In [ ]:
mydf = pd.concat([one, two])

In [ ]:
mydf

    A   B
0  A0  B0
1  A1  B1
2  A2  B2
3  A3  B3
0  C0  D0
1  C1  D1
2  C2  D2
3  C3  D3

In [ ]:
mydf.index = range (len(mydf))

In [ ]:
mydf

    A   B
0  A0  B0
1  A1  B1
2  A2  B2
3  A3  B3
4  C0  D0
5  C1  D1
6  C2  D2
7  C3  D3

## DataFrames - Merging

In [ ]:
# Inner merge
# Outer merge
# Left of Right merge

In [ ]:
reg = {'reg_id': [1, 2, 3, 4], 'name': ['Andrew', 'Bobo', 'Claire', 'David']}

In [ ]:
reg

{'reg_id': [1, 2, 3, 4], 'name': ['Andrew', 'Bobo', 'Claire', 'David']}

In [ ]:
log = {'login_id': [1, 2, 3, 4], 'name': ['Xavier', 'Andrew', 'Yolanda', 'Bobo']}

In [ ]:
registration = pd.DataFrame(reg)

In [ ]:
registration

   reg_id    name
0       1  Andrew
1       2    Bobo
2       3  Claire
3       4   David

In [ ]:
logins = pd.DataFrame(log)

In [ ]:
logins

   login_id     name
0         1   Xavier
1         2   Andrew
2         3  Yolanda
3         4     Bobo

In [ ]:
# help(pd.merge)

DataFrames - inner joins

In [ ]:
pd.merge(registration, logins, how = 'inner', on = 'name' )

   reg_id    name  login_id
0       1  Andrew         2
1       2    Bobo         4

In [ ]:
pd.merge(logins,registration, how = 'inner', on = 'name' )

   login_id    name  reg_id
0         2  Andrew       1
1         4    Bobo       2

Data Frames - Left OR rigth merge

In [ ]:
pd.merge(left=registration,right=logins,how ='left', on = 'name')

   reg_id    name  login_id
0       1  Andrew       2.0
1       2    Bobo       4.0
2       3  Claire       NaN
3       4   David       NaN

In [ ]:
pd.merge(left=registration,right=logins,how ='right', on = 'name')

   reg_id     name  login_id
0     NaN   Xavier         1
1     1.0   Andrew         2
2     NaN  Yolanda         3
3     2.0     Bobo         4

DataFrame - Outer join

In [ ]:
pd.merge(registration, logins, how = 'outer', on = 'name')

   reg_id     name  login_id
0     1.0   Andrew       2.0
1     2.0     Bobo       4.0
2     3.0   Claire       NaN
3     4.0    David       NaN
4     NaN   Xavier       1.0
5     NaN  Yolanda       3.0

In [ ]:
pd.merge(logins, registration, how = 'outer', on = 'name')

   login_id     name  reg_id
0       1.0   Xavier     NaN
1       2.0   Andrew     1.0
2       3.0  Yolanda     NaN
3       4.0     Bobo     2.0
4       NaN   Claire     3.0
5       NaN    David     4.0

Join the DataFrames on index instad of columns

In [ ]:
registration = registration.set_index('name')

In [ ]:
registration

        reg_id
name
Andrew       1
Bobo         2
Claire       3
David        4

In [ ]:
logins

   login_id     name
0         1   Xavier
1         2   Andrew
2         3  Yolanda
3         4     Bobo

In [ ]:
pd.merge(registration, logins, left_index = True, right_on = 'name', how = 'inner')

   reg_id  login_id    name
1       1         2  Andrew
3       2         4    Bobo

In [ ]:
registration

        reg_id
name
Andrew       1
Bobo         2
Claire       3
David        4

In [ ]:
registration = registration.reset_index()

In [ ]:
registration

     name  reg_id
0  Andrew       1
1    Bobo       2
2  Claire       3
3   David       4

In [ ]:
logins

   login_id     name
0         1   Xavier
1         2   Andrew
2         3  Yolanda
3         4     Bobo

In [ ]:
registration.columns

Index(['name', 'reg_id'], dtype='object')

In [ ]:
registration.columns = ['reg_name', 'reg_id']

In [ ]:
registration

  reg_name  reg_id
0   Andrew       1
1     Bobo       2
2   Claire       3
3    David       4

In [ ]:
results = pd.merge(registration, logins, how = 'inner', left_on = 'reg_name', right_on = 'name' )

In [ ]:
results

  reg_name  reg_id  login_id    name
0   Andrew       1         2  Andrew
1     Bobo       2         4    Bobo

In [ ]:
results.drop('reg_name', axis = 1)

   reg_id  login_id    name
0       1         2  Andrew
1       2         4    Bobo

In [ ]:
registration

  reg_name  reg_id
0   Andrew       1
1     Bobo       2
2   Claire       3
3    David       4

In [ ]:
registration.columns = ['name', 'id']

In [ ]:
registration

     name  id
0  Andrew   1
1    Bobo   2
2  Claire   3
3   David   4

In [ ]:
logins

   login_id     name
0         1   Xavier
1         2   Andrew
2         3  Yolanda
3         4     Bobo

In [ ]:
logins.columns = ['id', 'name']

In [ ]:
logins

   id     name
0   1   Xavier
1   2   Andrew
2   3  Yolanda
3   4     Bobo

In [ ]:
pd.merge(registration, logins, how = 'inner', on = 'name')

     name  id_x  id_y
0  Andrew     1     2
1    Bobo     2     4

In [ ]:
pd.merge(registration, logins, how = 'inner', on = 'name', suffixes = ('_reg', '_log'))

     name  id_reg  id_log
0  Andrew       1       2
1    Bobo       2       4

## Text Methods

In [1]:
import pandas as pd
import numpy as np

In [2]:
email = "cypherkrish@gmail.com"

In [4]:
email.split('@')

['cypherkrish', 'gmail.com']

In [7]:
names = pd.Series(['Andrew', 'bobo', 'clare', 'david', '5'])

In [8]:
names

0    Andrew
1      bobo
2     clare
3     david
4         5
dtype: object

In [9]:
names.str.upper()

0    ANDREW
1      BOBO
2     CLARE
3     DAVID
4         5
dtype: object

In [11]:
email.isdigit()

False

In [13]:
names.str.isdigit()

0    False
1    False
2    False
3    False
4     True
dtype: bool

In [14]:
tech_finance = ['GOOGLE, AMAZON , APPLE', 'JPM, BAC, GS']

In [18]:
tech_finance

['GOOGLE, AMAZON , APPLE', 'JPM, BAC, GS']

In [19]:
len(tech_finance)

2

In [20]:
tickers = pd.Series(tech_finance)

In [21]:
tickers

0    GOOGLE, AMAZON , APPLE
1              JPM, BAC, GS
dtype: object

In [23]:
tickers.str.split(',')

0    [GOOGLE,  AMAZON ,  APPLE]
1              [JPM,  BAC,  GS]
dtype: object

In [25]:
tickers.str.split(',')[0]

['GOOGLE', ' AMAZON ', ' APPLE']

In [26]:
tickers.str.split(',')[0][0]

'GOOGLE'

In [27]:
tickers.str.split(',')[0][2]

' APPLE'

In [29]:
tickers.str.split(',').str[0]

0    GOOGLE
1       JPM
dtype: object

In [30]:
tickers.str.split(',').str[1]

0     AMAZON
1         BAC
dtype: object

In [31]:
tickers.str.split(',').str[2]

0     APPLE
1        GS
dtype: object

In [32]:
tickers.str.split(',')

0    [GOOGLE,  AMAZON ,  APPLE]
1              [JPM,  BAC,  GS]
dtype: object

In [33]:
tickers.str.split(',', expand = True)

        0         1       2
0  GOOGLE   AMAZON    APPLE
1     JPM       BAC      GS

In [44]:
messy_names = pd.Series(['andrew   ', "bo:bo", "   claire   "])

In [45]:
messy_names

0       andrew
1           bo:bo
2       claire
dtype: object

In [46]:
messy_names[0]

'andrew   '

In [47]:
messy_names[1]

'bo:bo'

In [48]:
messy_names.str.replace(":", '').str.strip().str.capitalize()

0    Andrew
1      Bobo
2    Claire
dtype: object

In [49]:
# Define a cleanup functio

def cleanup (name):
  name = name.replace(":", "")
  name = name.strip()
  name = name.capitalize()

  return name

In [50]:
messy_names.apply(cleanup)

0    Andrew
1      Bobo
2    Claire
dtype: object

In [51]:
# Which is the best methd? using the above str.replace function or cleanup function?

In [52]:
import timeit

In [55]:
setup = '''
import pandas as pd
import numpy as np

messy_names = pd.Series(['andrew   ', "bo:bo", "   claire   "])

def cleanup (name):
  name = name.replace(":", "")
  name = name.strip()
  name = name.capitalize()

  return name

'''

stmt_pandas_str = '''
messy_names.str.replace(":",'').str.strip().str.capitalize()
'''

stmt_pandas_apply = '''
messy_names.apply(cleanup)
'''

stmt_pandas_vectorize = '''
np.vectorize(cleanup)(messy_names)

'''

In [56]:
timeit.timeit(setup = setup, stmt = stmt_pandas_str, number = 10000)

4.6220662309999625

In [57]:
timeit.timeit(setup = setup, stmt = stmt_pandas_apply, number = 10000)

1.5307102149999992

In [58]:
timeit.timeit(setup = setup, stmt = stmt_pandas_vectorize, number = 10000)

0.23904823900011252

## Date and time methods

In [2]:
import pandas as pd
import numpy as np

from datetime import datetime

In [3]:
myyear = 2015
mymonth = 1
myday = 1
myhour = 5
mymin = 30
mysec = 10

In [4]:
mydate = datetime(myyear, mymonth, myday)

In [5]:
mydate

datetime.datetime(2015, 1, 1, 0, 0)

In [6]:
mydatetime = datetime(myyear, mymonth, myday, myhour, mymin, mysec)

In [7]:
mydatetime

datetime.datetime(2015, 1, 1, 5, 30, 10)

In [8]:
mydatetime.year

2015

In [10]:
mydatetime.date()

datetime.date(2015, 1, 1)

In [11]:
myser = pd.Series(['Nov 3, 1990', '2000-1-1', None])

In [12]:
myser

0    Nov 3, 1990
1       2000-1-1
2           None
dtype: object

In [13]:
myser[0]

'Nov 3, 1990'

In [14]:
myser[0].year

AttributeError: ignored

In [15]:
pd.to_datetime(myser)

0   1990-11-03
1   2000-01-01
2          NaT
dtype: datetime64[ns]

In [16]:
# How to know date format ?

timeser = pd.to_datetime(myser)

In [17]:
timeser

0   1990-11-03
1   2000-01-01
2          NaT
dtype: datetime64[ns]

In [18]:
timeser[0]

Timestamp('1990-11-03 00:00:00')

In [19]:
timeser[0].year

1990

In [23]:
euro_date1 = "31-12-2000"

In [24]:
pd.to_datetime(euro_date1)

<ipython-input-24-d8a84802048b>:1: UserWarning: Parsing dates in DD/MM/YYYY format when dayfirst=False (the default) was specified. This may lead to inconsistently parsed dates! Specify a format to ensure consistent parsing.
  pd.to_datetime(euro_date1)

Timestamp('2000-12-31 00:00:00')

In [25]:
euro_date2 = "10-12-2000"

In [26]:
pd.to_datetime(euro_date2)

Timestamp('2000-10-12 00:00:00')

In [29]:
pd.to_datetime(euro_date2, dayfirst = True)

Timestamp('2000-12-10 00:00:00')

In [30]:
style_date =  '12--Dec--2020'

In [31]:
pd.to_datetime(style_date, format = '%d--%b--%Y')

Timestamp('2020-12-12 00:00:00')

In [33]:
custome_date = "12th of Dec 2000"

In [34]:
pd.to_datetime(custome_date)

Timestamp('2000-12-12 00:00:00')

In [35]:
sales = pd.read_csv("https://raw.githubusercontent.com/cypherkrish/PythonDataScience/main/Data/RetailSales_BeerWineLiquor.csv")

In [36]:
sales.head()

         DATE  MRTSSM4453USN
0  1992-01-01           1509
1  1992-02-01           1541
2  1992-03-01           1597
3  1992-04-01           1675
4  1992-05-01           1822

In [37]:
sales['DATE']

0      1992-01-01
1      1992-02-01
2      1992-03-01
3      1992-04-01
4      1992-05-01
          ...
335    2019-12-01
336    2020-01-01
337    2020-02-01
338    2020-03-01
339    2020-04-01
Name: DATE, Length: 340, dtype: object

In [38]:
sales['DATE'] = pd.to_datetime(sales['DATE'])

In [39]:
sales['DATE']

0     1992-01-01
1     1992-02-01
2     1992-03-01
3     1992-04-01
4     1992-05-01
         ...
335   2019-12-01
336   2020-01-01
337   2020-02-01
338   2020-03-01
339   2020-04-01
Name: DATE, Length: 340, dtype: datetime64[ns]

In [40]:
sales['DATE'][0].year

1992

In [42]:
sales_2 = pd.read_csv("https://raw.githubusercontent.com/cypherkrish/PythonDataScience/main/Data/RetailSales_BeerWineLiquor.csv", parse_dates = [0])

In [43]:
sales_2['DATE']

0     1992-01-01
1     1992-02-01
2     1992-03-01
3     1992-04-01
4     1992-05-01
         ...
335   2019-12-01
336   2020-01-01
337   2020-02-01
338   2020-03-01
339   2020-04-01
Name: DATE, Length: 340, dtype: datetime64[ns]

In [48]:
sales_2.head()

        DATE  MRTSSM4453USN
0 1992-01-01           1509
1 1992-02-01           1541
2 1992-03-01           1597
3 1992-04-01           1675
4 1992-05-01           1822

In [49]:
sales_2["DATE"].dt.month

0       1
1       2
2       3
3       4
4       5
       ..
335    12
336     1
337     2
338     3
339     4
Name: DATE, Length: 340, dtype: int64

In [50]:
sales_2['DATE'].dt.year

0      1992
1      1992
2      1992
3      1992
4      1992
       ...
335    2019
336    2020
337    2020
338    2020
339    2020
Name: DATE, Length: 340, dtype: int64

In [44]:
# Set DATE column as an index for the dataframe

sales = sales.set_index('DATE')

In [45]:
sales

            MRTSSM4453USN
DATE
1992-01-01           1509
1992-02-01           1541
1992-03-01           1597
1992-04-01           1675
1992-05-01           1822
...                   ...
2019-12-01           6630
2020-01-01           4388
2020-02-01           4533
2020-03-01           5562
2020-04-01           5207

[340 rows x 1 columns]

In [47]:
# resampl is for groupby

sales.resample(rule = 'A').mean()

            MRTSSM4453USN
DATE
1992-12-31    1807.250000
1993-12-31    1794.833333
1994-12-31    1841.750000
1995-12-31    1833.916667
1996-12-31    1929.750000
1997-12-31    2006.750000
1998-12-31    2115.166667
1999-12-31    2206.333333
2000-12-31    2375.583333
2001-12-31    2468.416667
2002-12-31    2491.166667
2003-12-31    2539.083333
2004-12-31    2682.416667
2005-12-31    2797.250000
2006-12-31    3001.333333
2007-12-31    3177.333333
2008-12-31    3292.000000
2009-12-31    3353.750000
2010-12-31    3450.083333
2011-12-31    3532.666667
2012-12-31    3697.083333
2013-12-31    3839.666667
2014-12-31    4023.833333
2015-12-31    4212.500000
2016-12-31    4434.416667
2017-12-31    4602.666667
2018-12-31    4830.666667
2019-12-31    4972.750000
2020-12-31    4922.500000

# Data Input and Output for Pandas

using CSV files

In [2]:
import pandas as pd

In [3]:
pd.read_csv("https://raw.githubusercontent.com/cypherkrish/PythonDataScience/main/Data/example.csv", index_col = 0)

     b   c   d
a
0    1   2   3
4    5   6   7
8    9  10  11
12  13  14  15

In [4]:
df = pd.read_csv("https://raw.githubusercontent.com/cypherkrish/PythonDataScience/main/Data/example.csv", index_col = 0)

In [5]:
df.to_csv('newfile.csv')

HTML Tables

In [6]:
import pandas as pd

In [7]:
!pip install lxml

Requirement already satisfied: lxml in /usr/local/lib/python3.10/dist-packages (4.9.3)

In [8]:
url = "https://en.wikipedia.org/wiki/World_population"

In [9]:
tables = pd.read_html(url)

In [10]:
len(tables)

29

In [11]:
tables[0]

,Population,1,2,3,4,5,6,7,8,9,10
0,Year,1804,1927,1960,1974,1987,1999,2011,2022,2037,2057
1,Years elapsed,"200,000+",123,33,14,13,12,12,11,15,20

In [12]:
tables[1]

,Region,2022 (percent),2030 (percent),2050 (percent)
0,Sub-Saharan Africa,"1,152 (14.51%)","1,401 (16.46%)","2,094 (21.62%)"
1,Northern Africa and Western Asia,549 (6.91%),617 (7.25%),771 (7.96%)
2,Central Asia and Southern Asia,"2,075 (26.13%)","2,248 (26.41%)","2,575 (26.58%)"
3,Eastern Asia and Southeastern Asia,"2,342 (29.49%)","2,372 (27.87%)","2,317 (23.92%)"
4,Europe and Northern America,"1,120 (14.10%)","1,129 (13.26%)","1,125 (11.61%)"
5,Latin America and the Caribbean,658 (8.29%),695 (8.17%),749 (7.73%)
6,Australia and New Zealand,31 (0.39%),34 (0.40%),38 (0.39%)
7,Oceania,14 (0.18%),15 (0.18%),20 (0.21%)
8,World,7942,8512,9687

In [14]:
tables[2]

    0                                                  1
0 NaN  Graphs are temporarily unavailable due to tech...

In [15]:
tables[3]

,Region,Density (inhabitants/km2),Population (millions),Most populous country,Most populous city (metropolitan area)
0,Asia,104.1,4641,"1,418,459,382 – India","13,515,000 – Tokyo Metropolis (37,400,000 – Gr..."
1,Africa,44.4,1340,"0,211,401,000 – Nigeria","09,500,000 – Cairo (20,076,000 – Greater Cairo)"
2,Europe,73.4,747,"0,146,171,000 – Russia, approx. 110 million in...","13,200,000 – Moscow (20,004,000 – Moscow metro..."
3,Latin America,24.1,653,"0,214,103,000 – Brazil","12,252,000 – São Paulo City (21,650,000 – São ..."
4,Northern America[note 1],14.9,368,"0,332,909,000 – United States","08,804,000 – New York City (23,582,649 – New Y..."
5,Oceania,5,42,"0,025,917,000 – Australia","05,367,000 – Sydney"
6,Antarctica,~0,0.004[89],N/A[note 2],"00,001,258 – McMurdo Station"

In [17]:
tables[4]

,Rank,Country / Dependency,Population,Percentage of the world,Date,Source (official or from the United Nations)
0,1,India,1425775850,NaN,14 Apr 2023,UN projection[92]
1,2,China,1412600000,NaN,31 Dec 2021,National annual estimate[93]
2,3,United States,335508924,NaN,14 Oct 2023,National population clock[94]
3,4,Indonesia,275773800,NaN,1 Jul 2022,National annual estimate[95]
4,5,Pakistan,229488994,NaN,1 Jul 2022,UN projection[96]
5,6,Nigeria,216746934,NaN,1 Jul 2022,UN projection[96]
6,7,Brazil,216773704,NaN,14 Oct 2023,National population clock[97]
7,8,Bangladesh,168220000,NaN,1 Jul 2020,Annual Population Estimate[98]
8,9,Russia,147190000,NaN,1 Oct 2021,2021 preliminary census results[99]
9,10,Mexico,128271248,NaN,31 Mar 2022,NaN

In [30]:
tables[4].columns

Index(['Rank', 'Country / Dependency', 'Population', 'Percentage of the world',
       'Date', 'Source (official or from the United Nations)'],
      dtype='object')

In [32]:
top10_Population = tables[4]

In [33]:
top10_Population

,Rank,Country / Dependency,Population,Percentage of the world,Date,Source (official or from the United Nations)
0,1,India,1425775850,NaN,14 Apr 2023,UN projection[92]
1,2,China,1412600000,NaN,31 Dec 2021,National annual estimate[93]
2,3,United States,335508924,NaN,14 Oct 2023,National population clock[94]
3,4,Indonesia,275773800,NaN,1 Jul 2022,National annual estimate[95]
4,5,Pakistan,229488994,NaN,1 Jul 2022,UN projection[96]
5,6,Nigeria,216746934,NaN,1 Jul 2022,UN projection[96]
6,7,Brazil,216773704,NaN,14 Oct 2023,National population clock[97]
7,8,Bangladesh,168220000,NaN,1 Jul 2020,Annual Population Estimate[98]
8,9,Russia,147190000,NaN,1 Oct 2021,2021 preliminary census results[99]
9,10,Mexico,128271248,NaN,31 Mar 2022,NaN

In [35]:
top10_Population.columns = ['Rank', 'Country', 'Population', 'Percentage of the world','Date', 'UN Souse']

In [39]:
top10_Population.drop('Percentage of the world',axis = 1)

,Rank,Country,Population,Date,UN Souse
0,1,India,1425775850,14 Apr 2023,UN projection[92]
1,2,China,1412600000,31 Dec 2021,National annual estimate[93]
2,3,United States,335508924,14 Oct 2023,National population clock[94]
3,4,Indonesia,275773800,1 Jul 2022,National annual estimate[95]
4,5,Pakistan,229488994,1 Jul 2022,UN projection[96]
5,6,Nigeria,216746934,1 Jul 2022,UN projection[96]
6,7,Brazil,216773704,14 Oct 2023,National population clock[97]
7,8,Bangladesh,168220000,1 Jul 2020,Annual Population Estimate[98]
8,9,Russia,147190000,1 Oct 2021,2021 preliminary census results[99]
9,10,Mexico,128271248,31 Mar 2022,NaN

In [40]:
top10_Population = top10_Population.drop('Percentage of the world',axis = 1)

In [41]:
top10_Population

,Rank,Country,Population,Date,UN Souse
0,1,India,1425775850,14 Apr 2023,UN projection[92]
1,2,China,1412600000,31 Dec 2021,National annual estimate[93]
2,3,United States,335508924,14 Oct 2023,National population clock[94]
3,4,Indonesia,275773800,1 Jul 2022,National annual estimate[95]
4,5,Pakistan,229488994,1 Jul 2022,UN projection[96]
5,6,Nigeria,216746934,1 Jul 2022,UN projection[96]
6,7,Brazil,216773704,14 Oct 2023,National population clock[97]
7,8,Bangladesh,168220000,1 Jul 2020,Annual Population Estimate[98]
8,9,Russia,147190000,1 Oct 2021,2021 preliminary census results[99]
9,10,Mexico,128271248,31 Mar 2022,NaN

In [42]:
top10_Population = top10_Population.set_index("Rank")

In [43]:
top10_Population

,Country,Population,Date,UN Souse
Rank,,,,
1,India,1425775850,14 Apr 2023,UN projection[92]
2,China,1412600000,31 Dec 2021,National annual estimate[93]
3,United States,335508924,14 Oct 2023,National population clock[94]
4,Indonesia,275773800,1 Jul 2022,National annual estimate[95]
5,Pakistan,229488994,1 Jul 2022,UN projection[96]
6,Nigeria,216746934,1 Jul 2022,UN projection[96]
7,Brazil,216773704,14 Oct 2023,National population clock[97]
8,Bangladesh,168220000,1 Jul 2020,Annual Population Estimate[98]
9,Russia,147190000,1 Oct 2021,2021 preliminary census results[99]
10,Mexico,128271248,31 Mar 2022,NaN

In [44]:
top10_Population.to_html('sample_table.html', index = False)

Read Excel files

install xlrd => to read the old excel files with .xls extension

install openpyxl => to read the new files with .xlsx extension

In [45]:
import pandas as pd

In [52]:
df = pd.read_excel("my_excel_file.xlsx", sheet_name = "First_Sheet")

In [53]:
df

    a   b   c   d
0   0   1   2   3
1   4   5   6   7
2   8   9  10  11
3  12  13  14  15

In [58]:
pd.ExcelFile("my_excel_file.xlsx").sheet_names

['First_Sheet']

In [60]:
work_book = pd.ExcelFile("my_excel_file.xlsx")

In [62]:
work_book.sheet_names

['First_Sheet']

In [63]:
excel_sheet_dict = pd.read_excel('my_excel_file.xlsx', sheet_name = None)

In [64]:
type(excel_sheet_dict)

dict

In [66]:
excel_sheet_dict.keys()

dict_keys(['First_Sheet'])

In [67]:
 excel_sheet_dict['First_Sheet']

    a   b   c   d
0   0   1   2   3
1   4   5   6   7
2   8   9  10  11
3  12  13  14  15

In [69]:
 excel_sheet_dict

{'First_Sheet':     a   b   c   d
 0   0   1   2   3
 1   4   5   6   7
 2   8   9  10  11
 3  12  13  14  15}

In [70]:
out_excel = excel_sheet_dict["First_Sheet"]

In [71]:
out_excel

    a   b   c   d
0   0   1   2   3
1   4   5   6   7
2   8   9  10  11
3  12  13  14  15

In [72]:
out_excel.to_excel("examle.xlsx", sheet_name = "First_Sheet", index = False)

SQL Datbase

Using the sqlalchemy python library

Pandas - Pivot Tables

In [73]:
import pandas as pd
import numpy as np

In [74]:
pd.read_csv("https://raw.githubusercontent.com/cypherkrish/PythonDataScience/main/Data/Sales_Funnel_CRM.csv")

,Account Number,Company,Contact,Account Manager,Product,Licenses,Sale Price,Status
0,2123398,Google,Larry Pager,Edward Thorp,Analytics,150,2100000,Presented
1,2123398,Google,Larry Pager,Edward Thorp,Prediction,150,700000,Presented
2,2123398,Google,Larry Pager,Edward Thorp,Tracking,300,350000,Under Review
3,2192650,BOBO,Larry Pager,Edward Thorp,Analytics,150,2450000,Lost
4,420496,IKEA,Elon Tusk,Edward Thorp,Analytics,300,4550000,Won
5,636685,Tesla Inc.,Elon Tusk,Edward Thorp,Analytics,300,2800000,Under Review
6,636685,Tesla Inc.,Elon Tusk,Edward Thorp,Prediction,150,700000,Presented
7,1216870,Microsoft,Will Grates,Edward Thorp,Tracking,300,350000,Under Review
8,2200450,Walmart,Will Grates,Edward Thorp,Analytics,150,2450000,Lost
9,405886,Apple,Cindy Phoner,Claude Shannon,Analytics,300,4550000,Won
10,470248,Exxon Mobile,Cindy Phoner,Claude Shannon,Analytics,150,2100000,Presented
11,698032,ATT,Cindy Phoner,Claude Shannon,Tracking,150,350000,Under Review
12,698032,ATT,Cindy Phoner,Claude Shannon,Prediction,150,700000,Presented
13,902797,CVS Health,Emma Gordian,Claude Shannon,Tracking,450,490000,Won
14,2046943,Salesforce,Emma Gordian,Claude Shannon,Analytics,750,7000000,Won
15,2169499,Cisco,Emma Gordian,Claude Shannon,Analytics,300,4550000,Lost
16,2169499,Cisco,Emma Gordian,Claude Shannon,GPS Positioning,300,350000,Presented

In [75]:
df = pd.read_csv("https://raw.githubusercontent.com/cypherkrish/PythonDataScience/main/Data/Sales_Funnel_CRM.csv")

In [76]:
df.head()

,Account Number,Company,Contact,Account Manager,Product,Licenses,Sale Price,Status
0,2123398,Google,Larry Pager,Edward Thorp,Analytics,150,2100000,Presented
1,2123398,Google,Larry Pager,Edward Thorp,Prediction,150,700000,Presented
2,2123398,Google,Larry Pager,Edward Thorp,Tracking,300,350000,Under Review
3,2192650,BOBO,Larry Pager,Edward Thorp,Analytics,150,2450000,Lost
4,420496,IKEA,Elon Tusk,Edward Thorp,Analytics,300,4550000,Won

In [77]:
help(pd.pivot)

Help on function pivot in module pandas.core.reshape.pivot:

pivot(data: 'DataFrame', *, index: 'IndexLabel | None' = None, columns: 'IndexLabel | None' = None, values: 'IndexLabel | None' = None) -> 'DataFrame'
    Return reshaped DataFrame organized by given index / column values.

    Reshape data (produce a "pivot" table) based on column values. Uses
    unique values from specified `index` / `columns` to form axes of the
    resulting DataFrame. This function does not support data
    aggregation, multiple values will result in a MultiIndex in the
    columns. See the :ref:`User Guide <reshaping>` for more on reshaping.

    Parameters
    ----------
    data : DataFrame
    index : str or object or a list of str, optional
        Column to use to make new frame's index. If None, uses
        existing index.

        .. versionchanged:: 1.1.0
           Also accept list of index names.

    columns : str or object or a list of str
        Column to use to make new frame's columns.

        .. versionchanged:: 1.1.0
           Also accept list of columns names.

    values : str, object or a list of the previous, optional
        Column(s) to use for populating new frame's values. If not
        specified, all remaining columns will be used and the result will
        have hierarchically indexed columns.

    Returns
    -------
    DataFrame
        Returns reshaped DataFrame.

    Raises
    ------
    ValueError:
        When there are any `index`, `columns` combinations with multiple
        values. `DataFrame.pivot_table` when you need to aggregate.

    See Also
    --------
    DataFrame.pivot_table : Generalization of pivot that can handle
        duplicate values for one index/column pair.
    DataFrame.unstack : Pivot based on the index values instead of a
        column.
    wide_to_long : Wide panel to long format. Less flexible but more
        user-friendly than melt.

    Notes
    -----
    For finer-tuned control, see hierarchical indexing documentation along
    with the related stack/unstack methods.

    Reference :ref:`the user guide <reshaping.pivot>` for more examples.

    Examples
    --------
    >>> df = pd.DataFrame({'foo': ['one', 'one', 'one', 'two', 'two',
    ...                            'two'],
    ...                    'bar': ['A', 'B', 'C', 'A', 'B', 'C'],
    ...                    'baz': [1, 2, 3, 4, 5, 6],
    ...                    'zoo': ['x', 'y', 'z', 'q', 'w', 't']})
    >>> df
        foo   bar  baz  zoo
    0   one   A    1    x
    1   one   B    2    y
    2   one   C    3    z
    3   two   A    4    q
    4   two   B    5    w
    5   two   C    6    t

    >>> df.pivot(index='foo', columns='bar', values='baz')
    bar  A   B   C
    foo
    one  1   2   3
    two  4   5   6

    >>> df.pivot(index='foo', columns='bar')['baz']
    bar  A   B   C
    foo
    one  1   2   3
    two  4   5   6

    >>> df.pivot(index='foo', columns='bar', values=['baz', 'zoo'])
          baz       zoo
    bar   A  B  C   A  B  C
    foo
    one   1  2  3   x  y  z
    two   4  5  6   q  w  t

    You could also assign a list of column names or a list of index names.

    >>> df = pd.DataFrame({
    ...        "lev1": [1, 1, 1, 2, 2, 2],
    ...        "lev2": [1, 1, 2, 1, 1, 2],
    ...        "lev3": [1, 2, 1, 2, 1, 2],
    ...        "lev4": [1, 2, 3, 4, 5, 6],
    ...        "values": [0, 1, 2, 3, 4, 5]})
    >>> df
        lev1 lev2 lev3 lev4 values
    0   1    1    1    1    0
    1   1    1    2    2    1
    2   1    2    1    3    2
    3   2    1    2    4    3
    4   2    1    1    5    4
    5   2    2    2    6    5

    >>> df.pivot(index="lev1", columns=["lev2", "lev3"],values="values")
    lev2    1         2
    lev3    1    2    1    2
    lev1
    1     0.0  1.0  2.0  NaN
    2     4.0  3.0  NaN  5.0

    >>> df.pivot(index=["lev1", "lev2"], columns=["lev3"],values="values")
          lev3    1    2
    lev1  lev2
       1     1  0.0  1.0
             2  2.0  NaN
       2     1  4.0  3.0
             2  NaN  5.0

    A ValueError is raised if there are any duplicates.

    >>> df = pd.DataFrame({"foo": ['one', 'one', 'two', 'two'],
    ...                    "bar": ['A', 'A', 'B', 'C'],
    ...                    "baz": [1, 2, 3, 4]})
    >>> df
       foo bar  baz
    0  one   A    1
    1  one   A    2
    2  two   B    3
    3  two   C    4

    Notice that the first two rows are the same for our `index`
    and `columns` arguments.

    >>> df.pivot(index='foo', columns='bar', values='baz')
    Traceback (most recent call last):
       ...
    ValueError: Index contains duplicate entries, cannot reshape

In [80]:
licenses = df[['Company', 'Product', 'Licenses']]

In [82]:
pd.pivot(data = licenses, index = 'Company', columns = 'Product', values = 'Licenses')

Product       Analytics  GPS Positioning  Prediction  Tracking
Company
 Google           150.0              NaN       150.0     300.0
ATT                 NaN              NaN       150.0     150.0
Apple             300.0              NaN         NaN       NaN
BOBO              150.0              NaN         NaN       NaN
CVS Health          NaN              NaN         NaN     450.0
Cisco             300.0            300.0         NaN       NaN
Exxon Mobile      150.0              NaN         NaN       NaN
IKEA              300.0              NaN         NaN       NaN
Microsoft           NaN              NaN         NaN     300.0
Salesforce        750.0              NaN         NaN       NaN
Tesla Inc.        300.0              NaN       150.0       NaN
Walmart           150.0              NaN         NaN       NaN

In [88]:
pd.pivot_table(df, index = "Company", aggfunc = 'sum')

<ipython-input-88-eca86f9de520>:1: FutureWarning: pivot_table dropped a column because it failed to aggregate. This behavior is deprecated and will raise in a future version of pandas. Select only the columns that can be aggregated.
  pd.pivot_table(df, index = "Company", aggfunc = 'sum')

              Account Number  Licenses  Sale Price
Company
 Google              6370194       600     3150000
ATT                  1396064       300     1050000
Apple                 405886       300     4550000
BOBO                 2192650       150     2450000
CVS Health            902797       450      490000
Cisco                4338998       600     4900000
Exxon Mobile          470248       150     2100000
IKEA                  420496       300     4550000
Microsoft            1216870       300      350000
Salesforce           2046943       750     7000000
Tesla Inc.           1273370       450     3500000
Walmart              2200450       150     2450000

In [90]:
pd.pivot_table(df, index = "Company", aggfunc = 'sum', values = ["Licenses", "Sale Price"])

# This avoids the summing the Account numbers :)

              Licenses  Sale Price
Company
 Google            600     3150000
ATT                300     1050000
Apple              300     4550000
BOBO               150     2450000
CVS Health         450      490000
Cisco              600     4900000
Exxon Mobile       150     2100000
IKEA               300     4550000
Microsoft          300      350000
Salesforce         750     7000000
Tesla Inc.         450     3500000
Walmart            150     2450000

In [91]:
df.groupby('Company').sum()

# The above is same as groupby

<ipython-input-91-9a040ecb7585>:1: FutureWarning: The default value of numeric_only in DataFrameGroupBy.sum is deprecated. In a future version, numeric_only will default to False. Either specify numeric_only or select only columns which should be valid for the function.
  df.groupby('Company').sum()

              Account Number  Licenses  Sale Price
Company
 Google              6370194       600     3150000
ATT                  1396064       300     1050000
Apple                 405886       300     4550000
BOBO                 2192650       150     2450000
CVS Health            902797       450      490000
Cisco                4338998       600     4900000
Exxon Mobile          470248       150     2100000
IKEA                  420496       300     4550000
Microsoft            1216870       300      350000
Salesforce           2046943       750     7000000
Tesla Inc.           1273370       450     3500000
Walmart              2200450       150     2450000

In [92]:
df.head()

,Account Number,Company,Contact,Account Manager,Product,Licenses,Sale Price,Status
0,2123398,Google,Larry Pager,Edward Thorp,Analytics,150,2100000,Presented
1,2123398,Google,Larry Pager,Edward Thorp,Prediction,150,700000,Presented
2,2123398,Google,Larry Pager,Edward Thorp,Tracking,300,350000,Under Review
3,2192650,BOBO,Larry Pager,Edward Thorp,Analytics,150,2450000,Lost
4,420496,IKEA,Elon Tusk,Edward Thorp,Analytics,300,4550000,Won

In [97]:
pd.pivot_table(df, index = ['Account Manager', 'Contact'], values = ['Sale Price'], columns = ['Product'], aggfunc = 'sum', fill_value =0)

                             Sale Price
Product                       Analytics GPS Positioning Prediction Tracking
Account Manager Contact
Claude Shannon  Cindy Phoner    6650000               0     700000   350000
                Emma Gordian   11550000          350000          0   490000
Edward Thorp    Elon Tusk       7350000               0     700000        0
                Larry Pager     4550000               0     700000   350000
                Will Grates     2450000               0          0   350000

In [98]:
pd.pivot_table(df, index = ['Account Manager', 'Contact'], values = ['Sale Price'], columns = ['Product'], aggfunc = [np.sum, np.mean], fill_value =0)

                                    sum                                      \
                             Sale Price
Product                       Analytics GPS Positioning Prediction Tracking
Account Manager Contact
Claude Shannon  Cindy Phoner    6650000               0     700000   350000
                Emma Gordian   11550000          350000          0   490000
Edward Thorp    Elon Tusk       7350000               0     700000        0
                Larry Pager     4550000               0     700000   350000
                Will Grates     2450000               0          0   350000

                                   mean
                             Sale Price
Product                       Analytics GPS Positioning Prediction Tracking
Account Manager Contact
Claude Shannon  Cindy Phoner    3325000               0     700000   350000
                Emma Gordian    5775000          350000          0   490000
Edward Thorp    Elon Tusk       3675000               0     700000        0
                Larry Pager     2275000               0     700000   350000
                Will Grates     2450000               0          0   350000

# Exercise